import React, { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, Clock3, Pencil, Plus, Search, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { blogApi, FinancialBlog, FinancialBlogInput } from '../api/blogApi';
import { useAuth } from '../context/AuthContext';

const blankForm: FinancialBlogInput = { title: '', summary: '', content: '' };
const dateLabel = (date: string) => new Date(date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
const readingTime = (content: string) => Math.max(1, Math.ceil(content.trim().split(/\s+/).length / 200));

export const BlogsLanding: React.FC = () => {
  const { role } = useAuth();
  const isAdmin = role === 'SYSTEM_ADMIN';
  const [blogs, setBlogs] = useState<FinancialBlog[]>([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editing, setEditing] = useState<FinancialBlog | null>(null);
  const [form, setForm] = useState<FinancialBlogInput>(blankForm);
  const [editorOpen, setEditorOpen] = useState(false);
  const [saving, setSaving] = useState(false);

  const load = async () => { setLoading(true); try { setBlogs(await blogApi.list()); setError(''); } catch { setError('Stories could not be loaded right now.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const openEditor = (blog?: FinancialBlog) => { setEditing(blog || null); setForm(blog ? { title: blog.title, summary: blog.summary, content: blog.content } : blankForm); setEditorOpen(true); };
  const closeEditor = () => { setEditing(null); setForm(blankForm); setEditorOpen(false); };
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const saved = editing ? await blogApi.update(editing.blog_id, form) : await blogApi.create(form); setBlogs(items => editing ? items.map(item => item.blog_id === saved.blog_id ? saved : item) : [saved, ...items]); closeEditor(); } catch (requestError: any) { setError(requestError?.userFriendlyMessage || 'Unable to save this story.'); } finally { setSaving(false); } };
  const remove = async (blog: FinancialBlog) => { if (!window.confirm(`Delete "${blog.title}"? This cannot be undone.`)) return; try { await blogApi.remove(blog.blog_id); setBlogs(items => items.filter(item => item.blog_id !== blog.blog_id)); } catch (requestError: any) { setError(requestError?.userFriendlyMessage || 'Unable to delete this story.'); } };
  const visibleBlogs = blogs.filter(blog => `${blog.title} ${blog.summary}`.toLowerCase().includes(query.toLowerCase()));

  return <div className="blog-page min-h-screen overflow-hidden bg-[#f8f6f1] text-slate-900">
    <section className="relative isolate overflow-hidden bg-[#861823] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_10%,rgba(215,131,45,.35),transparent_24%),radial-gradient(circle_at_10%_90%,rgba(255,255,255,.12),transparent_28%)]" /><div className="relative mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-20"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.15em] text-amber-200"><Sparkles className="h-3.5 w-3.5" /> Editorial financial guides</div><h1 className="mt-6 font-serif text-4xl font-semibold leading-tight sm:text-6xl">Clearer money decisions begin here.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/80 sm:text-lg">Practical explainers on borrowing, savings, credit and government financial support—made for everyday India.</p>{isAdmin && <div className="mt-7 inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs text-white/85"><ShieldCheck className="h-4 w-4 text-amber-200" /> Admin privileges active: reader accounts remain view-only.</div>}</div></div></section>
    <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-14"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#861823]">Latest stories</p><h2 className="mt-2 font-serif text-3xl font-semibold">Read, reflect, move forward.</h2></div>{isAdmin && <button onClick={() => openEditor()} className="inline-flex items-center gap-2 rounded-full bg-[#861823] px-4 py-2.5 text-sm font-bold text-white shadow-md transition hover:bg-[#6f1420]"><Plus className="h-4 w-4" /> New story</button>}</div>
      <div className="mt-8 flex flex-col gap-3 rounded-2xl bg-[#f7e9e9] p-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search financial guides..." className="w-full rounded-xl border-0 bg-white py-3 pl-11 pr-4 text-sm shadow-sm outline-none ring-[#861823] focus:ring-2" /></div><p className="px-2 text-xs font-semibold text-slate-500">{visibleBlogs.length} {visibleBlogs.length === 1 ? 'story' : 'stories'}</p></div>
      {error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
      {loading ? <div className="mt-8 space-y-5"><div className="h-52 animate-pulse rounded-2xl bg-[#f2dddd]" /><div className="h-52 animate-pulse rounded-2xl bg-[#f2dddd]" /></div> : visibleBlogs.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-[#c99da2] bg-white px-6 py-20 text-center"><BookOpen className="mx-auto h-8 w-8 text-[#861823]" /><h3 className="mt-4 font-serif text-2xl font-semibold">No stories found</h3><p className="mt-2 text-sm text-slate-500">Try another search or check back when new guides are published.</p></div> : <div className="mt-8 space-y-5">{visibleBlogs.map(blog => <article key={blog.blog_id} className="group w-full rounded-2xl bg-white p-6 shadow-sm ring-1 ring-[#f0dfe1] transition hover:-translate-y-0.5 hover:shadow-md sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><Link to={`/blogs/${blog.blog_id}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-[#f7e9e9] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-[#861823]">Financial guide</span><span className="inline-flex items-center gap-1 text-xs text-slate-500"><Clock3 className="h-3.5 w-3.5" /> {readingTime(blog.content)} min read</span></div><h3 className="mt-5 font-serif text-2xl font-semibold leading-tight text-slate-900 sm:text-3xl">{blog.title}</h3><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{blog.summary}</p><div className="mt-6 flex items-center justify-between border-t border-[#f5ebec] pt-4 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5 text-[#861823]" /> {dateLabel(blog.updated_at)}</span><span className="inline-flex items-center gap-1 font-bold text-[#861823]">Read story <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>{isAdmin && <div className="flex shrink-0 gap-2 border-t border-[#f5ebec] pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><button aria-label="Edit story" onClick={() => openEditor(blog)} className="rounded-full bg-[#f7e9e9] p-2.5 text-[#861823] transition hover:bg-[#efd4d7]"><Pencil className="h-4 w-4" /></button><button aria-label="Delete story" onClick={() => remove(blog)} className="rounded-full bg-red-50 p-2.5 text-red-700 transition hover:bg-red-100"><Trash2 className="h-4 w-4" /></button></div>}</div></article>)}</div>}
      <div className="mt-12 flex items-center gap-3 rounded-2xl bg-[#3c1424] p-6 text-white"><ShieldCheck className="h-7 w-7 shrink-0 text-amber-300" /><p className="text-sm leading-6 text-white/75">Every guide is published by the YojnaSetu editorial team. We focus on plain-language financial education, not personal financial advice.</p></div>
    </main>
    {isAdmin && editorOpen && <div className="fixed inset-0 z-[200] flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl font-semibold">{editing ? 'Edit story' : 'New story'}</h2><button type="button" onClick={closeEditor} className="rounded-full p-2 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><label className="mt-5 block text-sm font-bold">Title<input required minLength={3} maxLength={180} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3 font-normal" /></label><label className="mt-4 block text-sm font-bold">Summary<input required minLength={10} maxLength={500} value={form.summary} onChange={event => setForm({ ...form, summary: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3 font-normal" /></label><label className="mt-4 block text-sm font-bold">Financial guidance<textarea required minLength={20} maxLength={50000} rows={10} value={form.content} onChange={event => setForm({ ...form, content: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3 font-normal" /></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={closeEditor} className="rounded-full border border-slate-300 px-4 py-2.5 font-bold">Cancel</button><button disabled={saving} className="rounded-full bg-[#861823] px-5 py-2.5 font-bold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save story'}</button></div></form></div>}
  </div>;
};
