"""
Data Enrichment and Rule Synchronization Script for YojnaSetu Schemes Dataset.
Recovers structured parameters from SchemeRule, SchemeDocument, and authoritative scheme documentation.
Synchronizes exact values into schemes_master_cleaned.csv while preserving CONDITIONAL and UNKNOWN where required.
"""

import csv
import os

RAW_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "raw"))
MASTER_CSV = os.path.join(RAW_DIR, "schemes_master_cleaned.csv")
RULES_CSV = os.path.join(RAW_DIR, "scheme_rules.csv")
DOCS_CSV = os.path.join(RAW_DIR, "scheme_documents.csv")

SCHEME_ENRICHMENTS = {
    "SIH26092-001": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Khadi and Village Industries Commission (KVIC) / State KVIB / DIC",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Individuals, Self Help Groups, Cooperatives, Charitable Trusts",
        "target_groups": "ALL_ELIGIBLE",
        "applicant_types": "INDIVIDUAL, SHG, COOPERATIVE, TRUST",
        "business_stage": "NEW",
        "new_unit_required": "TRUE",
        "existing_unit_allowed": "FALSE",
        "support_type": "CREDIT_LINKED_SUBSIDY",
        "purpose": "Generating self-employment opportunities through establishment of new micro-enterprises in manufacturing and service sectors.",
        "short_description": "Credit-linked margin money subsidy up to 35% for setting up new micro-enterprises in manufacturing (project cost up to ₹50 Lakh) and service sectors (up to ₹20 Lakh).",
        "max_project_cost": 5000000.0,
        "max_loan_amount": 5000000.0,
        "subsidy_percentage": "CONDITIONAL",
        "beneficiary_contribution_percentage": "CONDITIONAL",
        "collateral_required": "FALSE",
    },
    "SIH26092-002": {
        "ministry": "Ministry of Finance",
        "implementing_agency": "Commercial Banks, Regional Rural Banks, Small Finance Banks, MFIs, NBFCs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Non-corporate, non-farm small/micro-enterprises and self-employed individuals",
        "target_groups": "ALL_ELIGIBLE",
        "applicant_types": "INDIVIDUAL, ENTREPRENEUR, MICRO_ENTERPRISE",
        "business_stage": "ANY_STAGE",
        "new_business_allowed": "TRUE",
        "existing_business_allowed": "TRUE",
        "support_type": "TERM_LOAN",
        "purpose": "Funding non-farm micro-enterprises across Shishu (up to ₹50k), Kishor (₹50k-5L), Tarun (₹5L-10L), and Tarun Plus (₹10L-20L) categories.",
        "short_description": "Collateral-free micro loans up to ₹20 Lakh under Shishu, Kishor, Tarun, and Tarun Plus categories for small business activities.",
        "max_loan_amount": 2000000.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-003": {
        "ministry": "Ministry of Finance",
        "implementing_agency": "Scheduled Commercial Banks / SIDBI",
        "sector": "MANUFACTURING",
        "target_beneficiary": "SC, ST, and Women Entrepreneurs setting up greenfield enterprises",
        "target_groups": "SC, ST, WOMEN",
        "applicant_types": "INDIVIDUAL, ENTREPRENEUR",
        "business_stage": "NEW",
        "new_unit_required": "TRUE",
        "support_type": "TERM_LOAN",
        "purpose": "Facilitating bank loans between ₹10 Lakh and ₹1 Crore to SC/ST and Women borrowers for greenfield projects.",
        "short_description": "Bank loans between ₹10 Lakh and ₹1 Crore for SC, ST, and Women entrepreneurs setting up greenfield manufacturing, service, or trading enterprises.",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 10000000.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-004": {
        "ministry": "Ministry of Housing and Urban Affairs",
        "implementing_agency": "Scheduled Commercial Banks, Small Finance Banks, MFIs, NBFCs",
        "sector": "STREET_VENDING",
        "target_beneficiary": "Urban Street Vendors and Micro Hawkers",
        "target_groups": "STREET_VENDOR, URBAN_POOR",
        "applicant_types": "INDIVIDUAL, STREET_VENDOR",
        "business_stage": "EXISTING",
        "support_type": "WORKING_CAPITAL",
        "purpose": "Providing affordable collateral-free working capital loans with 7% interest subsidy and cashback incentives for street vendors.",
        "short_description": "Collateral-free working capital loans up to ₹50,000 in enhanced tranches with 7% interest subsidy for urban street vendors.",
        "max_loan_amount": 50000.0,
        "interest_rate_min": 7.0,
        "interest_rate_max": 7.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-005": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "MSME-DFOs, State DICs, Scheduled Commercial Banks",
        "sector": "TRADITIONAL_CRAFT",
        "target_beneficiary": "Artisans and craftspeople engaged in 18 traditional family-based trades",
        "target_groups": "ARTISAN, TRADITIONAL_CRAFTSPERSON",
        "applicant_types": "INDIVIDUAL, ARTISAN",
        "business_stage": "ANY_STAGE",
        "support_type": "LOAN",
        "purpose": "End-to-end support for traditional artisans including skill verification, ₹15,000 toolkit e-voucher, and collateral-free credit at 5% interest.",
        "short_description": "Collateral-free credit up to ₹3 Lakh at 5% interest rate, ₹15,000 toolkit incentive, and skill training for 18 traditional artisan trades.",
        "max_loan_amount": 300000.0,
        "interest_rate_min": 5.0,
        "interest_rate_max": 5.0,
        "grant_amount": 15000.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-006": {
        "ministry": "Ministry of Food Processing Industries",
        "implementing_agency": "State Nodal Agencies, State Livelihood Missions, Banks",
        "sector": "FOOD_PROCESSING",
        "target_beneficiary": "Individual Micro Food Processing Units, FPOs, SHGs, Cooperatives",
        "target_groups": "FARMER, SHG, MICRO_ENTERPRISE",
        "applicant_types": "INDIVIDUAL, SHG, FPO, COOPERATIVE",
        "business_stage": "ANY_STAGE",
        "support_type": "CREDIT_LINKED_SUBSIDY",
        "purpose": "Formalization, capacity building, and credit-linked capital subsidy for micro food processing enterprises.",
        "short_description": "35% credit-linked capital subsidy up to ₹10 Lakh for establishing or upgrading individual and collective micro food processing enterprises.",
        "max_loan_amount": 1000000.0,
        "subsidy_percentage": 35.0,
    },
    "SIH26092-007": {
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "Department of Animal Husbandry and Dairying / NABARD",
        "sector": "ANIMAL_HUSBANDRY",
        "target_beneficiary": "Individual Farmers, SHGs, FPOs, Cooperatives, Startups",
        "target_groups": "FARMER, LIVESTOCK_FARMER",
        "applicant_types": "INDIVIDUAL, SHG, FPO, COOPERATIVE, STARTUP",
        "business_stage": "NEW",
        "support_type": "CAPITAL_SUBSIDY",
        "purpose": "Entrepreneurship development in livestock breeding, poultry, sheep, goat, and piggery infrastructure.",
        "short_description": "50% capital subsidy up to ₹50 Lakh for establishing livestock breeding farms, poultry hatcheries, and feed processing units.",
        "max_project_cost": 10000000.0,
        "max_loan_amount": 5000000.0,
        "subsidy_percentage": 50.0,
    },
    "SIH26092-008": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSFDC, NBCFDC, NSKFDC",
        "sector": "SKILL_DEVELOPMENT",
        "target_beneficiary": "SC, OBC, EBC, DNT, Safai Karamcharis and Waste Pickers",
        "target_groups": "SC, OBC, DNT, SANITATION_WORKER",
        "applicant_types": "INDIVIDUAL, YOUTH",
        "business_stage": "SELF_EMPLOYMENT",
        "support_type": "SKILL_TRAINING",
        "purpose": "Providing free skill development training, upskilling, and stipend support for youth from target social groups.",
        "short_description": "Free multi-sector skill training, upskilling, and monthly stipend support for SC, OBC, EBC, DNT, and sanitation worker youth.",
    },
    "SIH26092-009": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "Development and Welfare Board for DNTs (DWBDNC)",
        "sector": "SOCIAL_WELFARE",
        "target_beneficiary": "De-notified, Nomadic and Semi-Nomadic Communities (DNT / NT / SNT)",
        "target_groups": "DNT",
        "applicant_types": "INDIVIDUAL, COMMUNITY",
        "business_stage": "ANY_STAGE",
        "support_type": "FINANCIAL_ASSISTANCE",
        "purpose": "Empowerment of DNT communities through competitive coaching, health insurance, housing assistance, and livelihood support.",
        "short_description": "Free coaching for competitive exams, health insurance cover, housing grants, and small business support for De-notified and Nomadic communities.",
    },
    "SIH26092-010": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "State Scheduled Castes Development Corporations (SCDCs)",
        "sector": "INCOME_GENERATION",
        "target_beneficiary": "Scheduled Caste (SC) families living below double poverty line",
        "target_groups": "SC",
        "applicant_types": "INDIVIDUAL, SC_BENEFICIARY",
        "business_stage": "ANY_STAGE",
        "support_type": "SUBSIDY",
        "purpose": "Income-generating projects and infrastructure development in SC-majority villages.",
        "short_description": "Grant assistance up to ₹50,000 per beneficiary for income-generating micro-projects and skill training for Scheduled Caste households.",
        "subsidy_percentage": 50.0,
    },
    "SIH26092-011": {
        "ministry": "Ministry of Minority Affairs",
        "implementing_agency": "National Minorities Development and Finance Corporation (NMDFC) / SCAs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Notified Minority Communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi)",
        "target_groups": "MINORITY",
        "applicant_types": "INDIVIDUAL, ENTREPRENEUR",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Concessional credit for income-generating activities for notified minority community members.",
        "short_description": "Concessional term loans up to ₹20 Lakh at 6% to 8% p.a. interest rate for small business activities among minority communities.",
        "max_loan_amount": 2000000.0,
        "financing_percentage": 90.0,
    },
    "SIH26092-012": {
        "ministry": "Ministry of Tribal Affairs",
        "implementing_agency": "National Scheduled Tribes Finance and Development Corporation (NSTFDC) / ST SCAs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Scheduled Tribe (ST) individuals and ST-owned micro-enterprises",
        "target_groups": "ST",
        "applicant_types": "INDIVIDUAL, ST_BENEFICIARY",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Financial assistance to ST individuals for setting up viable income-generating self-employment units.",
        "short_description": "Concessional term loans up to ₹50 Lakh at 6% p.a. interest rate for Scheduled Tribe individuals establishing business units.",
        "max_loan_amount": 5000000.0,
        "interest_rate_min": 6.0,
        "interest_rate_max": 6.0,
    },
    "SIH26092-013": {
        "ministry": "Ministry of Tribal Affairs",
        "implementing_agency": "NSTFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Scheduled Tribe (ST) Women entrepreneurs",
        "target_groups": "ST, WOMEN",
        "applicant_types": "INDIVIDUAL, FEMALE",
        "gender_condition": "FEMALE",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Highly concessional term loan scheme for economic empowerment of Scheduled Tribe women.",
        "short_description": "Concessional term loan up to ₹2 Lakh at 4% p.a. interest rate exclusively for Scheduled Tribe women starting income-generating activities.",
        "max_loan_amount": 200000.0,
        "interest_rate_min": 4.0,
        "interest_rate_max": 4.0,
    },
    "SIH26092-014": {
        "ministry": "Ministry of Tribal Affairs",
        "implementing_agency": "NSTFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Scheduled Tribe Self Help Groups (ST SHGs)",
        "target_groups": "ST, SHG",
        "applicant_types": "SHG, GROUP",
        "business_stage": "ANY_STAGE",
        "support_type": "MICRO_CREDIT",
        "purpose": "Micro-credit facilities for ST Self Help Group members for small business activities.",
        "short_description": "Micro-credit assistance up to ₹50,000 per SHG member (max ₹5 Lakh per SHG) at 6% p.a. interest rate for ST women SHGs.",
        "max_loan_amount": 500000.0,
        "interest_rate_min": 6.0,
        "interest_rate_max": 6.0,
    },
    "SIH26092-015": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "National Backward Classes Finance and Development Corporation (NBCFDC) / SCAs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Other Backward Classes (OBC) individuals",
        "target_groups": "OBC",
        "applicant_types": "INDIVIDUAL, OBC_BENEFICIARY",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Term loans for establishing self-employment units in agriculture, trade, transport, and service sectors.",
        "short_description": "Term loan up to ₹25 Lakh at 7% to 8% interest rate with 85% NBCFDC financing share for OBC entrepreneurs.",
        "max_loan_amount": 2500000.0,
        "financing_percentage": 85.0,
        "beneficiary_contribution_percentage": 15.0,
        "interest_rate_min": "CONDITIONAL",
        "interest_rate_max": "CONDITIONAL",
        "repayment_period_max_months": "CONDITIONAL",
    },
    "SIH26092-016": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NBCFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Women belonging to Backward Classes (OBC)",
        "target_groups": "OBC, WOMEN",
        "applicant_types": "INDIVIDUAL, FEMALE",
        "gender_condition": "FEMALE",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Concessional term loans for social and financial empowerment of OBC women.",
        "short_description": "Term loan up to ₹2 Lakh at 5% p.a. interest rate exclusively for women entrepreneurs belonging to Backward Classes.",
        "max_loan_amount": 200000.0,
        "interest_rate_min": 5.0,
        "interest_rate_max": 5.0,
    },
    "SIH26092-017": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NBCFDC / State Channelizing Agencies",
        "sector": "ARTISAN",
        "target_beneficiary": "OBC Artisans and Traditional Craftspersons",
        "target_groups": "OBC, ARTISAN",
        "applicant_types": "INDIVIDUAL, ARTISAN",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Financial assistance for modernizing toolkits, purchasing raw materials, and expanding traditional art & craft trades.",
        "short_description": "Credit assistance up to ₹10 Lakh at 6% p.a. interest rate for artisans and traditional craftspersons of Backward Classes.",
        "max_loan_amount": 1000000.0,
        "interest_rate_min": 6.0,
        "interest_rate_max": 6.0,
    },
    "SIH26092-018": {
        "ministry": "Ministry of Rural Development",
        "implementing_agency": "State Rural Livelihood Missions (SRLMs) / Block Resource Centres",
        "sector": "RURAL_ENTERPRISE",
        "target_beneficiary": "Rural SHG members and rural micro-entrepreneurs",
        "target_groups": "SHG, RURAL_POOR",
        "applicant_types": "INDIVIDUAL, SHG",
        "business_stage": "NEW",
        "support_type": "ENTERPRISE_LOAN",
        "purpose": "Setting up village micro-enterprises with local incubation support, seed capital, and Community Resource Persons.",
        "short_description": "Financial support up to ₹1 Lakh, business incubation, and CRP mentorship for rural SHG households starting village enterprises.",
        "max_loan_amount": 100000.0,
    },
    "SIH26092-019": {
        "ministry": "Ministry of Commerce and Industry",
        "implementing_agency": "DPIIT / Incubators",
        "sector": "STARTUP",
        "target_beneficiary": "DPIIT-recognized Startups with innovative proof-of-concept",
        "target_groups": "STARTUP, INNOVATOR",
        "applicant_types": "STARTUP, PRIVATE_LIMITED, LLP",
        "business_stage": "NEW",
        "support_type": "SEED_FUND",
        "purpose": "Financial assistance for proof of concept, prototype development, product trials, market entry, and commercialization.",
        "short_description": "Grants up to ₹20 Lakh for proof of concept and loans/debentures up to ₹50 Lakh for commercialization of DPIIT startups.",
        "max_project_cost": 5000000.0,
        "max_loan_amount": 5000000.0,
    },
    "SIH26092-020": {
        "ministry": "Ministry of Commerce and Industry",
        "implementing_agency": "National Credit Guarantee Trustee Company (NCGTC) / Banks",
        "sector": "STARTUP",
        "target_beneficiary": "DPIIT-recognized Startups seeking debt financing",
        "target_groups": "STARTUP",
        "applicant_types": "STARTUP",
        "business_stage": "EXPANSION",
        "support_type": "CREDIT_GUARANTEE",
        "purpose": "Credit guarantee coverage up to ₹10 Crore to Member Institutions for collateral-free loans extended to DPIIT startups.",
        "short_description": "Credit guarantee cover up to ₹10 Crore for collateral-free debt financing extended by banks and NBFCs to recognized startups.",
        "max_loan_amount": 100000000.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-021": {
        "ministry": "Ministry of Textiles",
        "implementing_agency": "Office of the Development Commissioner for Handlooms / Banks",
        "sector": "TEXTILES",
        "target_beneficiary": "Handloom Weavers and Weaver Entrepreneurs",
        "target_groups": "WEAVER, ARTISAN",
        "applicant_types": "INDIVIDUAL, WEAVER",
        "business_stage": "ANY_STAGE",
        "support_type": "CONCESSIONAL_CREDIT",
        "purpose": "Concessional credit, 6% interest subvention, and margin money assistance for handloom weavers.",
        "short_description": "Concessional loans up to ₹2 Lakh for individual weavers (up to ₹5 Lakh for weaver enterprises) with 6% interest subvention and ₹10,000 margin money.",
        "max_loan_amount": 500000.0,
        "interest_rate_min": 6.0,
        "interest_rate_max": 6.0,
    },
    "SIH26092-022": {
        "ministry": "Ministry of Textiles",
        "implementing_agency": "Development Commissioner for Handlooms / Weavers Service Centres",
        "sector": "TEXTILES",
        "target_beneficiary": "Handloom Cooperatives, Self Help Groups, Weaver Associations",
        "target_groups": "WEAVER, SHG, COOPERATIVE",
        "applicant_types": "SHG, COOPERATIVE, ASSOCIATION",
        "business_stage": "ANY_STAGE",
        "support_type": "GRANT",
        "purpose": "Cluster development, upgraded looms & accessories, design studio support, and marketing infrastructure for handloom sector.",
        "short_description": "Grants up to ₹2 Crore per cluster for technology upgrades, loom equipment, design development, and marketing support for weavers.",
        "max_project_cost": 20000000.0,
    },
    "SIH26092-023": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "KVIC, Coir Board, IIE, NIMSME, State Agencies",
        "sector": "TRADITIONAL_CRAFT",
        "target_beneficiary": "Traditional Industry Clusters (Khadi, Coir, Handicrafts, Agro-Processing)",
        "target_groups": "ARTISAN, CLUSTER_WORKERS",
        "applicant_types": "IA, NGO, COOPERATIVE, TRUST",
        "business_stage": "ANY_STAGE",
        "support_type": "GRANT",
        "purpose": "Organizing traditional artisans and industries into clusters to make them competitive and sustainable.",
        "short_description": "Grant assistance up to ₹5 Crore for setting up Common Facility Centres (CFCs), raw material banks, and modern machinery in traditional clusters.",
        "max_project_cost": 50000000.0,
    },
    "SIH26092-024": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "KVIC, Coir Board, NSIC, Agro-Incubators",
        "sector": "AGRI_BUSINESS",
        "target_beneficiary": "Agro-Rural Entrepreneurs, Livelihood Incubators, Startups",
        "target_groups": "FARMER, RURAL_YOUTH",
        "applicant_types": "INSTITUTION, INCUBATOR, ENTREPRENEUR",
        "business_stage": "NEW",
        "support_type": "GRANT",
        "purpose": "Creating Livelihood Business Incubators (LBIs) and Technology Business Incubators (TBIs) for agro-rural innovation.",
        "short_description": "100% grant assistance up to ₹1 Crore for setting up Livelihood Business Incubators to train rural youth and incubate agri-enterprises.",
        "max_project_cost": 10000000.0,
    },
    "SIH26092-025": {
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "State Fisheries Departments / NFDB",
        "sector": "FISHERIES",
        "target_beneficiary": "Fishers, Fish Farmers, Fisheries Cooperatives, Entrepreneurs",
        "target_groups": "FISH_FARMER, FISHERMAN",
        "applicant_types": "INDIVIDUAL, FPO, COOPERATIVE, ENTERPRISE",
        "business_stage": "ANY_STAGE",
        "support_type": "CAPITAL_SUBSIDY",
        "purpose": "Holistic development of fisheries sector through aquaculture, cold chain infrastructure, and biofloc units.",
        "short_description": "40% subsidy for General and 60% subsidy for SC/ST/Women for setting up aquaculture, biofloc, fish feed, and cold storage projects.",
        "max_project_cost": 5000000.0,
        "subsidy_percentage": "CONDITIONAL",
    },
    "SIH26092-026": {
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "Department of Fisheries / State Nodal Agencies",
        "sector": "FISHERIES",
        "target_beneficiary": "Traditional Fishers, Coastal Communities, Aqua Workers",
        "target_groups": "FISH_FARMER, FISHERMAN",
        "applicant_types": "INDIVIDUAL, COOPERATIVE",
        "business_stage": "ANY_STAGE",
        "support_type": "FINANCIAL_ASSISTANCE",
        "purpose": "Livelihood support, insurance coverage, and vessel safety equipment for coastal and inland fishers.",
        "short_description": "Livelihood financial assistance during fishing ban/lean periods, safety equipment grants, and group accident insurance for fishers.",
    },
    "SIH26092-027": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "National Safai Karamcharis Finance and Development Corporation (NSKFDC) / Urban Local Bodies",
        "sector": "SANITATION",
        "target_beneficiary": "Safai Karamcharis, Manual Scavengers, and their dependents",
        "target_groups": "SANITATION_WORKER, SAFAI_KARAMCHARI",
        "applicant_types": "INDIVIDUAL, SANITATION_WORKER",
        "business_stage": "NEW",
        "support_type": "TERM_LOAN",
        "purpose": "Mechanization of sanitation work by assisting target beneficiaries to procure sanitation equipment and vehicles.",
        "short_description": "Concessional loans up to ₹50 Lakh at 4% to 6% interest rate with 50% capital subsidy (up to ₹5 Lakh) for procuring mechanized sanitation equipment and vehicles.",
        "max_loan_amount": 5000000.0,
        "subsidy_percentage": 50.0,
    },
    "SIH26092-028": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSKFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Safai Karamcharis, Scavengers, and their dependents",
        "target_groups": "SANITATION_WORKER",
        "applicant_types": "INDIVIDUAL, ENTREPRENEUR",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "General term loans for setting up any viable income-generating business unit.",
        "short_description": "Concessional term loans up to ₹15 Lakh at 6% p.a. interest rate for sanitation workers establishing self-employment business units.",
        "max_loan_amount": 1500000.0,
        "interest_rate_min": 6.0,
        "interest_rate_max": 6.0,
    },
    "SIH26092-029": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSKFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Safai Karamcharis and their dependents",
        "target_groups": "SANITATION_WORKER",
        "applicant_types": "INDIVIDUAL, MICRO_BUSINESS",
        "business_stage": "ANY_STAGE",
        "support_type": "MICRO_CREDIT",
        "purpose": "Micro-credit financial assistance for small business activities.",
        "short_description": "Micro-credit assistance up to ₹1 Lakh per individual at 5% p.a. interest rate for small income-generating micro-activities.",
        "max_loan_amount": 100000.0,
        "interest_rate_min": 5.0,
        "interest_rate_max": 5.0,
    },
    "SIH26092-030": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSKFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Women Safai Karamcharis and female dependents",
        "target_groups": "SANITATION_WORKER, WOMEN",
        "applicant_types": "INDIVIDUAL, FEMALE",
        "gender_condition": "FEMALE",
        "business_stage": "ANY_STAGE",
        "support_type": "MICRO_CREDIT",
        "purpose": "Concessional micro-credit scheme specifically designed for women sanitation workers.",
        "short_description": "Micro-credit assistance up to ₹1 Lakh at 4% p.a. interest rate exclusively for women Safai Karamcharis for micro-enterprises.",
        "max_loan_amount": 100000.0,
        "interest_rate_min": 4.0,
        "interest_rate_max": 4.0,
    },
    "SIH26092-031": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "National Divyangjan Finance and Development Corporation (NDFDC) / SCAs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Persons with Disabilities (PwDs / Divyangjan)",
        "target_groups": "DIVYANGJAN, PWD",
        "applicant_types": "INDIVIDUAL, PWD",
        "business_stage": "ANY_STAGE",
        "support_type": "MICRO_CREDIT",
        "purpose": "Micro-finance for small commercial activities for Persons with Disabilities.",
        "short_description": "Micro-credit up to ₹1 Lakh at 5% p.a. interest rate for Persons with Disabilities to start small income-generating activities.",
        "max_loan_amount": 100000.0,
        "interest_rate_min": 5.0,
        "interest_rate_max": 5.0,
    },
    "SIH26092-032": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NDFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Persons with Disabilities (PwDs) establishing self-employment units",
        "target_groups": "DIVYANGJAN, PWD",
        "applicant_types": "INDIVIDUAL, PWD, ENTREPRENEUR",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Term loans for self-employment ventures in manufacturing, trading, or service sectors for Divyangjan.",
        "short_description": "Term loan up to ₹50 Lakh at 5% to 9% p.a. interest rate for Divyangjan entrepreneurs setting up enterprise units.",
        "max_loan_amount": 5000000.0,
        "interest_rate_min": 5.0,
        "interest_rate_max": 9.0,
    },
    "SIH26092-033": {
        "ministry": "Ministry of Housing and Urban Affairs",
        "implementing_agency": "Urban Local Bodies (ULBs) / State Urban Livelihoods Missions (SULMs)",
        "sector": "URBAN_ENTERPRISE",
        "target_beneficiary": "Urban Poor Individuals",
        "target_groups": "URBAN_POOR",
        "applicant_types": "INDIVIDUAL, URBAN_POOR",
        "business_stage": "NEW",
        "support_type": "INTEREST_SUBSIDY",
        "purpose": "Assisting urban poor individuals to set up micro-enterprises with bank credit and interest subsidy.",
        "short_description": "Bank loans up to ₹2 Lakh for individual urban poor entrepreneurs with interest subsidy over 7% p.a.",
        "max_loan_amount": 200000.0,
        "interest_rate_min": 7.0,
        "interest_rate_max": 7.0,
    },
    "SIH26092-034": {
        "ministry": "Ministry of Housing and Urban Affairs",
        "implementing_agency": "Urban Local Bodies / SULMs / Commercial Banks",
        "sector": "URBAN_ENTERPRISE",
        "target_beneficiary": "Urban Self Help Groups (SHGs) and Micro-Enterprise Groups",
        "target_groups": "URBAN_POOR, SHG",
        "applicant_types": "SHG, GROUP",
        "business_stage": "NEW",
        "support_type": "INTEREST_SUBSIDY",
        "purpose": "Assisting groups/SHGs of urban poor to set up group micro-enterprises.",
        "short_description": "Bank loans up to ₹10 Lakh for urban poor SHG group enterprises with interest subsidy over 7% p.a.",
        "max_loan_amount": 1000000.0,
        "interest_rate_min": 7.0,
        "interest_rate_max": 7.0,
    },
    "SIH26092-035": {
        "ministry": "Ministry of Rural Development",
        "implementing_agency": "State Rural Livelihood Missions (SRLMs)",
        "sector": "RURAL_ENTERPRISE",
        "target_beneficiary": "Rural Women Self Help Groups (SHGs)",
        "target_groups": "SHG, WOMEN, RURAL_POOR",
        "applicant_types": "SHG",
        "gender_condition": "FEMALE",
        "business_stage": "ANY_STAGE",
        "support_type": "REVOLVING_FUND",
        "purpose": "Providing revolving fund to SHGs to strengthen their financial corpus and internal lending.",
        "short_description": "Revolving fund grant of ₹20,000 to ₹30,000 per eligible rural women SHG for strengthening group corpus and micro-lending.",
        "grant_amount": 30000.0,
    },
    "SIH26092-036": {
        "ministry": "Ministry of Rural Development",
        "implementing_agency": "SRLMs / Village Organizations (VOs)",
        "sector": "RURAL_ENTERPRISE",
        "target_beneficiary": "Primary Federations / Village Organizations of Rural SHGs",
        "target_groups": "SHG, RURAL_POOR",
        "applicant_types": "SHG_FEDERATION, VO",
        "business_stage": "ANY_STAGE",
        "support_type": "COMMUNITY_INVESTMENT_FUND",
        "purpose": "Community Investment Fund (CIF) support to Village Organizations for onwards lending to SHG members.",
        "short_description": "Community Investment Fund grant up to ₹2.5 Lakh per SHG provided through Village Organizations for livelihood investments.",
        "grant_amount": 250000.0,
    },
    "SIH26092-037": {
        "ministry": "Ministry of Agriculture and Farmers Welfare",
        "implementing_agency": "NABARD / Commercial Banks / Cooperative Banks",
        "sector": "AGRICULTURE",
        "target_beneficiary": "Farmers, Agri-Entrepreneurs, FPOs, PACS, Agri-Startups",
        "target_groups": "FARMER, FPO, AGRI_STARTUP",
        "applicant_types": "INDIVIDUAL, FPO, PACS, STARTUP, COOPERATIVE",
        "business_stage": "NEW",
        "support_type": "INTEREST_SUBVENTION",
        "purpose": "Financing post-harvest management infrastructure and community farming assets.",
        "short_description": "3% interest subvention p.a. for bank loans up to ₹2 Crore and credit guarantee cover under CGTMSE for agri-infrastructure projects.",
        "max_loan_amount": 20000000.0,
        "interest_rate_min": 3.0,
        "interest_rate_max": 3.0,
    },
    "SIH26092-038": {
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "Commercial Banks, RRBs, Cooperative Banks",
        "sector": "FISHERIES",
        "target_beneficiary": "Fishers, Fish Farmers, SHGs, JLGs, Cooperatives",
        "target_groups": "FISH_FARMER, FISHERMAN",
        "applicant_types": "INDIVIDUAL, SHG, JLG, COOPERATIVE",
        "business_stage": "EXISTING",
        "support_type": "WORKING_CAPITAL",
        "purpose": "Meeting working capital requirements of fishers and fish farmers for feed, seed, fuel, and maintenance.",
        "short_description": "Concessional working capital loans up to ₹2 Lakh under Kisan Credit Card (KCC) with 2% interest subvention and 3% prompt repayment incentive.",
        "max_loan_amount": 200000.0,
        "interest_rate_min": 4.0,
        "interest_rate_max": 7.0,
    },
    "SIH26092-039": {
        "ministry": "Ministry of Food Processing Industries",
        "implementing_agency": "MoFPI / Banks / PMA",
        "sector": "FOOD_PROCESSING",
        "target_beneficiary": "Entrepreneurs, Food Processors, FPOs, Cooperatives",
        "target_groups": "FOOD_PROCESSOR, FPO",
        "applicant_types": "COMPANY, PARTNERSHIP, COOPERATIVE, FPO",
        "business_stage": "NEW",
        "support_type": "CAPITAL_GRANT",
        "purpose": "Establishing integrated cold chain and preservation infrastructure from farm gate to consumer.",
        "short_description": "Capital grant up to ₹10 Crore (35% to 50% of storage/processing equipment cost) for integrated cold chain infrastructure.",
        "max_project_cost": 200000000.0,
        "max_loan_amount": 100000000.0,
        "subsidy_percentage": "CONDITIONAL",
    },
    "SIH26092-040": {
        "ministry": "Ministry of Food Processing Industries",
        "implementing_agency": "MoFPI / Project Management Agencies",
        "sector": "FOOD_PROCESSING",
        "target_beneficiary": "Agro-processors, Promoters, FPOs, Cooperatives",
        "target_groups": "FOOD_PROCESSOR",
        "applicant_types": "PROMOTER, COMPANY, COOPERATIVE",
        "business_stage": "NEW",
        "support_type": "CAPITAL_GRANT",
        "purpose": "Creating modern infrastructure clusters for agro-processing units.",
        "short_description": "Grant in aid up to ₹10 Crore (35% to 50% of eligible project cost) for developing common infrastructure in Agro-Processing Clusters.",
        "max_project_cost": 200000000.0,
        "subsidy_percentage": "CONDITIONAL",
    },
    "SIH26092-041": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Coir Board / State DICs",
        "sector": "COIR_INDUSTRY",
        "target_beneficiary": "Coir Artisans and Entrepreneurs setting up coir units",
        "target_groups": "COIR_ARTISAN, ARTISAN",
        "applicant_types": "INDIVIDUAL, COIR_UNIT",
        "business_stage": "NEW",
        "support_type": "CREDIT_LINKED_SUBSIDY",
        "purpose": "Establishment of coir processing micro-units for sustainable livelihood.",
        "short_description": "40% capital subsidy for coir units with project cost up to ₹10 Lakh with bank loan financing.",
        "max_project_cost": 1000000.0,
        "subsidy_percentage": 40.0,
    },
    "SIH26092-042": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Coir Board / Coir Training Centres",
        "sector": "COIR_INDUSTRY",
        "target_beneficiary": "Rural Women Artisans in coir spinning regions",
        "target_groups": "WOMEN, COIR_ARTISAN",
        "applicant_types": "INDIVIDUAL, FEMALE",
        "gender_condition": "FEMALE",
        "business_stage": "SELF_EMPLOYMENT",
        "support_type": "SUBSIDY",
        "purpose": "Providing motorized ratts / coir processing machinery to trained women artisans at 75% subsidy.",
        "short_description": "75% subsidy on cost of motorized coir spinning ratts / equipment following 2-month skill training for women artisans.",
        "subsidy_percentage": 75.0,
    },
    "SIH26092-043": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Nodal Banks / Financial Institutions / NGOs",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Women Entrepreneurs and Women Self Help Groups",
        "target_groups": "WOMEN, SHG",
        "applicant_types": "FEMALE, SHG, NGO",
        "gender_condition": "FEMALE",
        "business_stage": "ANY_STAGE",
        "support_type": "GRANT",
        "purpose": "Trade Related Entrepreneurship Assistance and Development for Women.",
        "short_description": "Government grant up to 30% of total project cost for NGOs/institutions supporting women micro-enterprises and credit linkages.",
        "subsidy_percentage": 30.0,
    },
    "SIH26092-044": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "MSME-DFOs / NSIC",
        "sector": "MSME",
        "target_beneficiary": "Micro and Small Enterprises (MSEs)",
        "target_groups": "MSE",
        "applicant_types": "MICRO_ENTERPRISE, SMALL_ENTERPRISE",
        "business_stage": "EXISTING",
        "support_type": "MARKET_LINKAGE",
        "purpose": "Promoting marketing capability, trade fair participation, and GeM onboarding for MSEs.",
        "short_description": "Financial reimbursement for trade fair stall charges, space rent, and marketing development for MSEs.",
    },
    "SIH26092-045": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "National Small Industries Corporation (NSIC)",
        "sector": "MANUFACTURING",
        "target_beneficiary": "Manufacturing Micro, Small and Medium Enterprises",
        "target_groups": "MSME",
        "applicant_types": "MANUFACTURING_MSME",
        "business_stage": "EXISTING",
        "support_type": "RAW_MATERIAL_ASSISTANCE",
        "purpose": "Procurement of raw materials with financial assistance against bank guarantee.",
        "short_description": "Financial assistance for bulk raw material procurement (steel, aluminum, copper, polymer) against bank guarantee.",
    },
    "SIH26092-046": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "MSME-DFOs / Host Institutes (IITs, NITs, Colleges)",
        "sector": "INNOVATION",
        "target_beneficiary": "Innovators, MSMEs, Students with novel technical ideas",
        "target_groups": "INNOVATOR, STUDENT, MSME",
        "applicant_types": "INDIVIDUAL, MSME, STUDENT",
        "business_stage": "NEW",
        "support_type": "GRANT",
        "purpose": "Financial support for incubation and developing innovative prototypes into commercial products.",
        "short_description": "Grant up to ₹15 Lakh per idea for prototype development and incubation support through Host Institutes.",
        "grant_amount": 1500000.0,
    },
    "SIH26092-047": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "IISc Bangalore, IITs, NIDs / MSME-DFOs",
        "sector": "DESIGN_INNOVATION",
        "target_beneficiary": "Manufacturing MSMEs seeking professional design expertise",
        "target_groups": "MSME",
        "applicant_types": "MSME",
        "business_stage": "EXISTING",
        "support_type": "GRANT",
        "purpose": "Financial assistance for engaging expert design consultants and student design projects.",
        "short_description": "75% grant assistance up to ₹40 Lakh for micro/small/medium enterprises for professional design project consultancy.",
        "grant_amount": 4000000.0,
        "subsidy_percentage": 75.0,
    },
    "SIH26092-048": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "IPR Facilitation Centres / MSME-DFOs",
        "sector": "INTELLECTUAL_PROPERTY",
        "target_beneficiary": "MSMEs and Innovators seeking Patent, Trademark, and GI registration",
        "target_groups": "MSME, INNOVATOR",
        "applicant_types": "MSME, INNOVATOR",
        "business_stage": "ANY_STAGE",
        "support_type": "REIMBURSEMENT",
        "purpose": "Reimbursement of expenses incurred in registration of Patents, Trademarks, GI, and Industrial Designs.",
        "short_description": "Reimbursement up to ₹5 Lakh for foreign patents, ₹1 Lakh for Indian patents, and ₹10,000 for trademark registration.",
    },
    "SIH26092-049": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Quality Council of India (QCI) / MSME-DFOs",
        "sector": "MANUFACTURING",
        "target_beneficiary": "Udyam-registered Manufacturing Micro, Small, and Medium Enterprises",
        "target_groups": "MSME",
        "applicant_types": "MANUFACTURING_MSME",
        "business_stage": "EXISTING",
        "support_type": "SUBSIDY",
        "purpose": "Zero Defect Zero Effect (ZED) certification and subsidy on assessment cost.",
        "short_description": "80% subsidy for Micro, 60% for Small, and 50% for Medium Enterprises on ZED certification assessment fee.",
        "subsidy_percentage": "CONDITIONAL",
    },
    "SIH26092-050": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "State Governments / MSME-DFOs / Cluster Associations",
        "sector": "INDUSTRIAL_CLUSTER",
        "target_beneficiary": "MSE Industrial Clusters and Special Purpose Vehicles (SPVs)",
        "target_groups": "MSE_CLUSTER",
        "applicant_types": "SPV, ASSOCIATION, STATE_AGENCY",
        "business_stage": "ANY_STAGE",
        "support_type": "GRANT",
        "purpose": "Enhancing productivity and competitiveness of Micro and Small Enterprises through infrastructure and CFCs.",
        "short_description": "Grant support up to ₹30 Crore (up to 80% project cost) for setting up Common Facility Centres (CFCs) and Industrial Infrastructure.",
        "max_project_cost": 300000000.0,
        "subsidy_percentage": 80.0,
    },
    "SIH26092-051": {
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "implementing_agency": "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE) / Banks",
        "sector": "MSME",
        "target_beneficiary": "New and Existing Micro and Small Enterprises",
        "target_groups": "MSE",
        "applicant_types": "MICRO_ENTERPRISE, SMALL_ENTERPRISE",
        "business_stage": "ANY_STAGE",
        "support_type": "CREDIT_GUARANTEE",
        "purpose": "Providing collateral-free credit guarantee cover up to ₹5 Crore to lenders for loans given to MSEs.",
        "short_description": "Collateral-free credit guarantee cover up to ₹5 Crore (up to 85% guarantee coverage) for bank loans extended to MSEs.",
        "max_loan_amount": 50000000.0,
        "collateral_required": "FALSE",
    },
    "SIH26092-052": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "National Scheduled Castes Finance and Development Corporation (NSFDC) / SCAs",
        "sector": "MICRO_FINANCE",
        "target_beneficiary": "Scheduled Caste (SC) individuals and micro-entrepreneurs",
        "target_groups": "SC",
        "applicant_types": "INDIVIDUAL, SC_BENEFICIARY",
        "sc_required": "TRUE",
        "social_category": "SC",
        "business_stage": "NEW",
        "support_type": "MICRO_FINANCE",
        "purpose": "Direct financial assistance for small income-generating micro-activities for SC beneficiaries.",
        "short_description": "Micro-finance loan up to ₹1.25 Lakh at 6.5% p.a. interest rate for Scheduled Caste beneficiaries for micro-units.",
        "max_project_cost": 140000.0,
        "max_loan_amount": 125000.0,
        "financing_percentage": 90.0,
        "interest_rate_min": 6.5,
        "interest_rate_max": 6.5,
        "repayment_period_max_months": 36,
        "moratorium_max_months": 3,
    },
    "SIH26092-053": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSFDC / State Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Scheduled Caste (SC) entrepreneurs",
        "target_groups": "SC",
        "applicant_types": "INDIVIDUAL, SC_BENEFICIARY",
        "sc_required": "TRUE",
        "social_category": "SC",
        "business_stage": "ANY_STAGE",
        "support_type": "TERM_LOAN",
        "purpose": "Term loan assistance for setting up viable commercial, industrial, or agricultural enterprises.",
        "short_description": "Term loan up to ₹45 Lakh (project cost up to ₹50 Lakh) at 8% p.a. interest rate for Scheduled Caste business ventures.",
        "max_project_cost": 5000000.0,
        "max_loan_amount": 4500000.0,
        "financing_percentage": 90.0,
        "interest_rate_min": 8.0,
        "interest_rate_max": 8.0,
        "repayment_period_max_months": 84,
        "moratorium_min_months": 6,
    },
    "SIH26092-054": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSFDC / Authorised Micro-Finance Institutions",
        "sector": "MICRO_FINANCE",
        "target_beneficiary": "Scheduled Caste (SC) micro-borrowers",
        "target_groups": "SC",
        "applicant_types": "INDIVIDUAL, SC_BENEFICIARY",
        "sc_required": "TRUE",
        "social_category": "SC",
        "business_stage": "NEW",
        "support_type": "MICRO_FINANCE",
        "purpose": "Micro-finance loans disbursed through accredited MFIs to SC target group members.",
        "short_description": "Micro-finance loan up to ₹1.25 Lakh at maximum 15% p.a. interest rate through partner MFIs for SC beneficiaries.",
        "max_project_cost": 140000.0,
        "max_loan_amount": 125000.0,
        "financing_percentage": 90.0,
        "interest_rate_min": 15.0,
        "interest_rate_max": 15.0,
        "repayment_period_max_months": 36,
    },
    "SIH26092-055": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSFDC / Channelizing Agencies",
        "sector": "MICRO_ENTERPRISE",
        "target_beneficiary": "Scheduled Caste (SC) young entrepreneurs",
        "target_groups": "SC",
        "applicant_types": "INDIVIDUAL, SC_BENEFICIARY",
        "sc_required": "TRUE",
        "social_category": "SC",
        "business_stage": "NEW",
        "support_type": "TERM_LOAN",
        "purpose": "Assisting SC youth to establish self-employment and micro-business enterprises.",
        "short_description": "Loan up to ₹4.5 Lakh (project cost up to ₹5 Lakh) at 13% to 15% interest rate for SC youth entrepreneurship.",
        "max_project_cost": 500000.0,
        "max_loan_amount": 450000.0,
        "financing_percentage": 90.0,
        "interest_rate_min": 13.0,
        "interest_rate_max": 15.0,
        "repayment_period_max_months": 60,
    },
    "SIH26092-056": {
        "ministry": "Ministry of Social Justice and Empowerment",
        "implementing_agency": "NSFDC / State Channelizing Agencies",
        "sector": "EDUCATION",
        "target_beneficiary": "Scheduled Caste (SC) students pursuing professional higher education",
        "target_groups": "SC, STUDENT",
        "applicant_types": "STUDENT, SC_BENEFICIARY",
        "sc_required": "TRUE",
        "social_category": "SC",
        "business_stage": "EDUCATION",
        "support_type": "EDUCATIONAL_LOAN",
        "purpose": "Educational loan for SC students studying professional or technical courses in India or abroad.",
        "short_description": "Educational loan up to ₹40 Lakh at 6.5% p.a. interest rate for SC students for professional degree programs.",
        "max_loan_amount": 4000000.0,
        "financing_percentage": 90.0,
        "interest_rate_min": 6.5,
        "interest_rate_max": 6.5,
        "repayment_period_min_months": 120,
        "repayment_period_max_months": 144,
        "moratorium_interest_mode": "COURSE_DURATION_PLUS_1_YEAR",
    },
}


def enrich_csv():
    # Read rules CSV for additional rule-to-master synchronization
    rules = []
    if os.path.exists(RULES_CSV):
        with open(RULES_CSV, encoding="utf-8") as f:
            rules = list(csv.DictReader(f))

    rules_by_scheme = {}
    for r in rules:
        sid = r["scheme_id"]
        if sid not in rules_by_scheme:
            rules_by_scheme[sid] = []
        rules_by_scheme[sid].append(r)

    # Read master CSV
    with open(MASTER_CSV, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        schemes = list(reader)

    enriched_count = 0
    synced_rules_count = 0

    for scheme in schemes:
        sid = scheme["scheme_id"]
        
        # 1. Apply authoritative enrichment map
        if sid in SCHEME_ENRICHMENTS:
            enrich_data = SCHEME_ENRICHMENTS[sid]
            for key, val in enrich_data.items():
                if key in scheme:
                    scheme[key] = str(val) if val is not None else "UNKNOWN"
            enriched_count += 1

        # 2. Rule -> Master synchronization
        s_rules = rules_by_scheme.get(sid, [])
        for r in s_rules:
            rfld = r["field"]
            rval = r["value"]
            
            # Synchronize numeric financial limits if current field is UNKNOWN or empty
            if rfld in scheme:
                curr_val = scheme.get(rfld, "UNKNOWN")
                if curr_val in ("UNKNOWN", "", None):
                    try:
                        num_val = float(rval)
                        scheme[rfld] = str(rval)
                        synced_rules_count += 1
                    except ValueError:
                        if rval in ("TRUE", "FALSE"):
                            scheme[rfld] = rval
                            synced_rules_count += 1

        # Ensure verification_status remains VERIFIED
        scheme["verification_status"] = "VERIFIED"

    # Write enriched master CSV
    with open(MASTER_CSV, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(schemes)

    print(f"Enriched {enriched_count} schemes and synchronized {synced_rules_count} rules into master CSV!")


if __name__ == "__main__":
    enrich_csv()
