"""Add more provenance fields to Partner

Revision ID: 3ba96b5c61ae
Revises: eb296256d045
Create Date: 2026-08-29 13:46:21.233634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba96b5c61ae'
down_revision: Union[str, Sequence[str], None] = 'eb296256d045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_notes', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('source_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordinates_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coordinates_verified', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('coordinates_verified')
        batch_op.drop_column('coordinates_source')
        batch_op.drop_column('source_document')
        batch_op.drop_column('source_category')
        batch_op.drop_column('verification_notes')

    # ### end Alembic commands ###
