"""Add geo and NPA metrics to Partner

Revision ID: 5459eca8aeea
Revises: g70b2041e014
Create Date: 2026-08-29 12:26:32.008714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5459eca8aeea'
down_revision: Union[str, Sequence[str], None] = 'g70b2041e014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
