"""Add geocoding provenance columns to Partner

Revision ID: 83ac17d36697
Revises: ad00d3f222e9
Create Date: 2026-08-29 15:47:01.295089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ac17d36697'
down_revision: Union[str, Sequence[str], None] = 'ad00d3f222e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocoding_provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('geocoding_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('geocoding_confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('geocoding_query', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('geocoding_display_name', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('geocoding_display_name')
        batch_op.drop_column('geocoding_query')
        batch_op.drop_column('geocoded_at')
        batch_op.drop_column('geocoding_confidence')
        batch_op.drop_column('geocoding_status')
        batch_op.drop_column('geocoding_provider')

    # ### end Alembic commands ###
