"""Add scheme_specific_mapping_available to Partner

Revision ID: ad00d3f222e9
Revises: 3ba96b5c61ae
Create Date: 2026-08-29 13:47:01.480117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad00d3f222e9'
down_revision: Union[str, Sequence[str], None] = '3ba96b5c61ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheme_specific_mapping_available', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('scheme_specific_mapping_available')

    # ### end Alembic commands ###
