"""create application tables

Revision ID: cb50a85f4845
Revises: 31390ec68281
Create Date: 2026-08-27 13:12:20.719541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb50a85f4845'
down_revision: Union[str, Sequence[str], None] = '31390ec68281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('profile_snapshot', sa.Text(), nullable=True, comment='JSON string snapshot of beneficiary profile at application/submission time'),
    sa.Column('eligibility_snapshot', sa.Text(), nullable=True, comment='JSON string snapshot of eligibility evaluation result'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('app_document_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['scheme_documents.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('app_document_id')
    )
    op.create_index(op.f('ix_application_documents_app_document_id'), 'application_documents', ['app_document_id'], unique=False)
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_history_id'), 'application_status_history', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_status_history_history_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_app_document_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
