"""Initial scheme schema

Revision ID: d460464e3311
Revises: 
Create Date: 2026-08-27 12:27:03.408685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd460464e3311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('scheme_type', sa.String(length=100), nullable=True),
    sa.Column('source_organization', sa.String(length=255), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('implementing_agency', sa.String(length=255), nullable=True),
    sa.Column('scheme_status', sa.String(length=50), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('target_beneficiary', sa.Text(), nullable=True),
    sa.Column('applicant_types', sa.Text(), nullable=True),
    sa.Column('marginalized_group', sa.String(length=100), nullable=True),
    sa.Column('target_groups', sa.Text(), nullable=True),
    sa.Column('entrepreneur_type', sa.String(length=100), nullable=True),
    sa.Column('sc_required', sa.String(length=50), nullable=True),
    sa.Column('social_category', sa.Text(), nullable=True),
    sa.Column('gender_condition', sa.String(length=50), nullable=True),
    sa.Column('gender_requirement', sa.String(length=50), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_min_raw', sa.String(length=50), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('age_max_raw', sa.String(length=50), nullable=True),
    sa.Column('income_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_limit_raw', sa.String(length=50), nullable=True),
    sa.Column('income_operator', sa.String(length=20), nullable=True),
    sa.Column('income_definition', sa.String(length=100), nullable=True),
    sa.Column('state_restriction', sa.String(length=50), nullable=True),
    sa.Column('state_coverage', sa.Text(), nullable=True),
    sa.Column('district_restriction', sa.String(length=50), nullable=True),
    sa.Column('district_coverage', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.Column('business_types', sa.Text(), nullable=True),
    sa.Column('business_stage', sa.String(length=50), nullable=True),
    sa.Column('new_unit_required', sa.String(length=50), nullable=True),
    sa.Column('new_business_allowed', sa.String(length=50), nullable=True),
    sa.Column('existing_unit_allowed', sa.String(length=50), nullable=True),
    sa.Column('existing_business_allowed', sa.String(length=50), nullable=True),
    sa.Column('business_registration_required', sa.String(length=50), nullable=True),
    sa.Column('enterprise_size_requirement', sa.String(length=100), nullable=True),
    sa.Column('education_applicable', sa.String(length=100), nullable=True),
    sa.Column('vocational_training_applicable', sa.String(length=100), nullable=True),
    sa.Column('support_type', sa.Text(), nullable=True),
    sa.Column('benefit_description', sa.Text(), nullable=True),
    sa.Column('loan_available', sa.String(length=50), nullable=True),
    sa.Column('min_project_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_project_cost_raw', sa.String(length=50), nullable=True),
    sa.Column('max_project_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_project_cost_raw', sa.String(length=50), nullable=True),
    sa.Column('minimum_loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('minimum_loan_amount_raw', sa.String(length=50), nullable=True),
    sa.Column('maximum_loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maximum_loan_amount_raw', sa.String(length=50), nullable=True),
    sa.Column('min_loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_loan_amount_raw', sa.String(length=50), nullable=True),
    sa.Column('max_loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_loan_amount_raw', sa.String(length=50), nullable=True),
    sa.Column('financing_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('financing_percentage_raw', sa.String(length=50), nullable=True),
    sa.Column('beneficiary_contribution_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('beneficiary_contribution_percentage_raw', sa.String(length=50), nullable=True),
    sa.Column('subsidy_available', sa.String(length=50), nullable=True),
    sa.Column('subsidy_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('subsidy_percentage_raw', sa.String(length=50), nullable=True),
    sa.Column('subsidy_details', sa.Text(), nullable=True),
    sa.Column('grant_available', sa.String(length=50), nullable=True),
    sa.Column('grant_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('grant_amount_raw', sa.String(length=50), nullable=True),
    sa.Column('interest_rate_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('interest_rate_min_raw', sa.String(length=50), nullable=True),
    sa.Column('interest_rate_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('interest_rate_max_raw', sa.String(length=50), nullable=True),
    sa.Column('interest_rate_type', sa.String(length=50), nullable=True),
    sa.Column('repayment_period_min_months', sa.Integer(), nullable=True),
    sa.Column('repayment_period_min_months_raw', sa.String(length=50), nullable=True),
    sa.Column('repayment_period_max_months', sa.Integer(), nullable=True),
    sa.Column('repayment_period_max_months_raw', sa.String(length=50), nullable=True),
    sa.Column('repayment_frequency', sa.String(length=50), nullable=True),
    sa.Column('moratorium_min_months', sa.Integer(), nullable=True),
    sa.Column('moratorium_min_months_raw', sa.String(length=50), nullable=True),
    sa.Column('moratorium_max_months', sa.Integer(), nullable=True),
    sa.Column('moratorium_max_months_raw', sa.String(length=50), nullable=True),
    sa.Column('moratorium_interest_mode', sa.String(length=100), nullable=True),
    sa.Column('collateral_required', sa.String(length=50), nullable=True),
    sa.Column('security_required', sa.Text(), nullable=True),
    sa.Column('training_available', sa.String(length=50), nullable=True),
    sa.Column('equipment_support', sa.String(length=50), nullable=True),
    sa.Column('market_support', sa.String(length=50), nullable=True),
    sa.Column('working_capital_support', sa.String(length=50), nullable=True),
    sa.Column('application_mode', sa.String(length=100), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('official_portal', sa.Text(), nullable=True),
    sa.Column('application_steps', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('helpline', sa.String(length=255), nullable=True),
    sa.Column('official_source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('source_published_date', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.String(length=50), nullable=True),
    sa.Column('effective_to', sa.String(length=50), nullable=True),
    sa.Column('scheme_version', sa.String(length=50), nullable=True),
    sa.Column('previous_version', sa.String(length=50), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('last_verified_date', sa.String(length=50), nullable=True),
    sa.Column('searchable_tags', sa.Text(), nullable=True),
    sa.Column('raw_source_row', sa.Text(), nullable=True),
    sa.Column('legacy_priority_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_schemes_ministry'), 'schemes', ['ministry'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_id'), 'schemes', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_name'), 'schemes', ['scheme_name'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_status'), 'schemes', ['scheme_status'], unique=False)
    op.create_index(op.f('ix_schemes_scheme_type'), 'schemes', ['scheme_type'], unique=False)
    op.create_index(op.f('ix_schemes_sector'), 'schemes', ['sector'], unique=False)
    op.create_table('scheme_changelogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_changelogs_scheme_id'), 'scheme_changelogs', ['scheme_id'], unique=False)
    op.create_table('scheme_documents',
    sa.Column('document_id', sa.String(length=50), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('applicant_type', sa.String(length=50), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_scheme_documents_scheme_id'), 'scheme_documents', ['scheme_id'], unique=False)
    op.create_table('scheme_rules',
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('parent_product_id', sa.String(length=50), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('condition_group', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.String(length=50), nullable=True),
    sa.Column('effective_to', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_scheme_rules_scheme_id'), 'scheme_rules', ['scheme_id'], unique=False)
    op.create_table('scheme_verifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('last_verified_date', sa.String(length=50), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('normalization_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_verifications_scheme_id'), 'scheme_verifications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_verifications_verification_status'), 'scheme_verifications', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_verifications_verification_status'), table_name='scheme_verifications')
    op.drop_index(op.f('ix_scheme_verifications_scheme_id'), table_name='scheme_verifications')
    op.drop_table('scheme_verifications')
    op.drop_index(op.f('ix_scheme_rules_scheme_id'), table_name='scheme_rules')
    op.drop_table('scheme_rules')
    op.drop_index(op.f('ix_scheme_documents_scheme_id'), table_name='scheme_documents')
    op.drop_table('scheme_documents')
    op.drop_index(op.f('ix_scheme_changelogs_scheme_id'), table_name='scheme_changelogs')
    op.drop_table('scheme_changelogs')
    op.drop_index(op.f('ix_schemes_sector'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_type'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_status'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_name'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_ministry'), table_name='schemes')
    op.drop_table('schemes')
    # ### end Alembic commands ###
