"""Add provenance fields to Partner

Revision ID: eb296256d045
Revises: 5459eca8aeea
Create Date: 2026-08-29 13:40:54.247650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb296256d045'
down_revision: Union[str, Sequence[str], None] = '5459eca8aeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('source_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), server_default='UNVERIFIED', nullable=False))
        batch_op.add_column(sa.Column('verified_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('source_date')
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
