"""
Comprehensive Translation Script for All Regional Indian Languages
Translates all compare, common, dashboard, partnerLocator, and calculator keys
into bn, mr, ta, te, gu, kn, ml, pa, or, as.
"""

import json
import os

LOCALES_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "01frontend", "src", "i18n", "locales")

REGIONAL_TRANSLATIONS = {
    "mr": {
        "common": {
            "status": "स्थिती",
            "view": "पहा",
            "filter": "फिल्टर",
            "official": "अधिकृत",
            "prev": "मागील",
            "verified": "सत्यापित",
            "viewAll": "सर्व पहा",
            "warning": "चेतावणी",
            "yes": "होय",
            "no": "नाही"
        },
        "compare": {
            "applyOfficial": "अधिकृत पोर्टलवर अर्ज करा",
            "benefitSummary": "सहाय्य रचना",
            "browseSchemes": "योजना शोधा",
            "calculateEmi": "ईएमआय मोजा",
            "calculatorAction": "कॅल्क्युलेटर कृती",
            "documentsList": "आवश्यक कागदपत्रे",
            "eligibilityStatus": "पात्रता स्थिती",
            "eligible": "✓ पात्र",
            "financialAssistance": "आर्थिक सहाय्य आणि पत अटी",
            "findPartners": "अधिकृत भागीदार शोधा",
            "geographicCoverage": "भौगोलिक व्याप्ती",
            "incomeLimit": "उत्पन्न मर्यादा",
            "interestRate": "व्याज दर",
            "loanAvailable": "कर्ज सुविधा उपलब्ध",
            "mandatoryDocuments": "अनिवार्य कागदपत्रे",
            "maxLoan": "कमाल नमूद कर्ज रक्कम",
            "ministry": "मंत्रालय / विभाग",
            "moratorium": "सवलत कालावधी (मोरेटोरियम)",
            "occupation": "व्यवसाय / कार्यक्षेत्र",
            "officialSource": "अधिकृत स्रोत",
            "remove": "काढून टाका",
            "repaymentTenure": "परतफेड कालावधी",
            "requiredDocs": "आवश्यक कागदपत्रे",
            "schemeOverview": "योजना विहंगावलोकन",
            "schemePurpose": "योजनेचा उद्देश आणि लाभ",
            "schemeType": "योजनेचा प्रकार / वर्ग",
            "secApplication": "अर्ज आणि प्रवेश मार्ग",
            "secDocuments": "कागदपत्रे आणि पुरावे",
            "secEligibility": "पात्रता निकष",
            "secFinancial": "आर्थिक सहाय्य आणि पत अटी",
            "secOverview": "योजना विहंगावलोकन कार्ड",
            "secVerification": "सरकारी पडताळणी आणि कव्हरेज",
            "socialCategory": "सामाजिक प्रवर्ग आणि लिंग",
            "subsidy": "सबसिडी / अनुदान",
            "tenure": "परतफेड कालावधी",
            "title": "योजनांची तुलना करा",
            "viewDetails": "तपशील पहा",
            "govVerification": "सरकारी पडताळणी",
            "lastVerified": "अंतिम पडताळणी तारीख",
            "notApplicable": "लागू नाही",
            "notSpecified": "उपलब्ध सरकारी माहितीत नमूद नाही",
            "marginMoney": "लाभार्थी योगदान",
            "collateral": "तारण आवश्यकता",
            "applicationMode": "अर्ज पद्धत",
            "applicationRoute": "अर्ज मार्ग",
            "officialPortal": "अधिकृत पोर्टल",
            "channelAgency": "अंमलबजावणी संस्था",
            "highestStated": "कमाल नमूद",
            "lowestStated": "किमान नमूद व्याज दर",
            "secOverviewSubtitle": "मूळ रचना, मंत्रालय आणि भौगोलिक कार्यक्षेत्र",
            "secEligibilitySubtitle": "वय, उत्पन्न, सामाजिक प्रवर्ग आणि व्यवसायाचे निकष",
            "secFinancialSubtitle": "कर्ज मर्यादा, व्याज दर, सबसिडी आणि तारण अटी",
            "secDocumentsSubtitle": "अनिवार्य कागदपत्रे, ओळखपत्रे आणि प्रमाणपत्रे",
            "secApplicationSubtitle": "अर्ज प्रक्रिया, अधिकृत पोर्टल आणि मदत केंद्र",
            "secVerificationSubtitle": "सरकारी पडताळणी, अधिकृत स्रोत आणि राज्य व्याप्ती",
            "profileAssessmentSubtitle": "तुमच्या प्रोफाइलवर आधारित वैयक्तिकृत पात्रता तपासणी",
            "creditFacility": "कर्ज सुविधा",
            "noIncomeLimit": "कोणतीही अनिवार्य मर्यादा नाही",
            "standardMarginMoney": "प्रकल्प खर्चाच्या ५% - १०%",
            "noCollateral": "कोणतेही तारण आवश्यक नाही (सीजीटीएमएसई हमी)",
            "bankAssisted": "चॅनेल भागीदार / बँक सहाय्य",
            "directOnlinePortal": "थेट ऑनलाइन पोर्टल",
            "channelPartner": "चॅनेल भागीदार / संस्था",
            "noCreditWelfare": "नाही — अनुदान / सबसिडी / कल्याणकारी योजना"
        }
    },
    "bn": {
        "common": {
            "status": "অবস্থা",
            "view": "দেখুন",
            "filter": "ফিল্টার",
            "official": "দাপ্তরিক",
            "prev": "পূর্ববর্তী",
            "verified": "যাচাইকৃত",
            "viewAll": "সব দেখুন",
            "warning": "সতর্কতা",
            "yes": "হ্যাঁ",
            "no": "না"
        },
        "compare": {
            "applyOfficial": "দাপ্তরিক পোর্টালে আবেদন করুন",
            "benefitSummary": "সহায়তা কাঠামো",
            "browseSchemes": "প্রকল্প ব্রাউজ করুন",
            "calculateEmi": "ইএমআই হিসাব করুন",
            "calculatorAction": "ক্যালকুলেটর ব্যবস্থা",
            "documentsList": "প্রয়োজনীয় নথিপত্র",
            "eligibilityStatus": "যোগ্যতার স্থিতি",
            "eligible": "✓ যোগ্য",
            "financialAssistance": "আর্থিক সহায়তা ও ঋণের শর্তাবলী",
            "findPartners": "অনুমোদিত অংশীদার খুঁজুন",
            "geographicCoverage": "ভৌগোলিক পরিধি",
            "incomeLimit": "আয়সীমা",
            "interestRate": "সুদের হার",
            "loanAvailable": "ঋণ সুবিধা উপলব্ধ",
            "mandatoryDocuments": "বাধ্যতামূলক নথিপত্র",
            "maxLoan": "সর্বোচ্চ ঘোষিত ঋণ",
            "ministry": "মন্ত্রণালয় / বিভাগ",
            "moratorium": "মোরেটোরিয়াম সময়কাল",
            "occupation": "পেশা / খাত",
            "officialSource": "দাপ্তরিক উৎস",
            "remove": "মুছুন",
            "repaymentTenure": "পরিশোধের মেয়াদ",
            "requiredDocs": "প্রয়োজনীয় নথিপত্র",
            "schemeOverview": "প্রকল্পের বিবরণ",
            "schemePurpose": "উদ্দেশ্য ও আর্থিক সুবিধা",
            "schemeType": "প্রকল্পের আর্থিক বিভাগ",
            "secApplication": "আবেদন ও প্রবেশ পথ",
            "secDocuments": "নথিপত্র ও প্রমাণপত্র",
            "secEligibility": "যোগ্যতার মানদণ্ড",
            "secFinancial": "আর্থিক সহায়তা ও ঋণের শর্তাবলী",
            "secOverview": "প্রকল্প সংক্ষিপ্ত বিবরণ",
            "secVerification": "সরকারি যাচাইকরণ ও পরিধি",
            "socialCategory": "সামাজিক বিভাগ ও লিঙ্গ",
            "subsidy": "ভর্তুকি / অনুদান",
            "tenure": "পরিশোধের সময়সীমা",
            "title": "প্রকল্পের তুলনা করুন",
            "viewDetails": "বিস্তারিত দেখুন",
            "govVerification": "সরকারি যাচাইকরণ",
            "lastVerified": "সর্বশেষ যাচাইয়ের তারিখ",
            "notApplicable": "প্রযোজ্য নয়",
            "notSpecified": "উৎস নথিতে নির্দিষ্ট করা নেই",
            "marginMoney": "সুবিধাভোগীর নিজস্ব অংশ",
            "collateral": "জামানতের প্রয়োজনীয়তা",
            "applicationMode": "আবেদন মাধ্যম",
            "applicationRoute": "আবেদনের পথ",
            "officialPortal": "দাপ্তরিক পোর্টাল",
            "channelAgency": "বাস্তবায়নকারী সংস্থা",
            "highestStated": "সর্বোচ্চ ঘোষিত",
            "lowestStated": "সর্বনিম্ন ঘোষিত সুদের হার",
            "secOverviewSubtitle": "মূল উদ্দেশ্য, পৃষ্ঠপোষক মন্ত্রণালয় ও ভৌগোলিক পরিধি",
            "secEligibilitySubtitle": "বয়স, আয়, সামাজিক বিভাগ ও পেশার শর্ত",
            "secFinancialSubtitle": "ঋণসীমা, সুদের হার, ভর্তুকি ও জামানতের শর্তাবলী",
            "secDocumentsSubtitle": "বাধ্যতামূলক পরিচয়পত্র ও অন্যান্য প্রমাণপত্র",
            "secApplicationSubtitle": "আবেদন প্রক্রিয়া, অনলাইন পোর্টাল ও স্থানীয় সহায়তা কেন্দ্র",
            "secVerificationSubtitle": "সরকারি তথ্য যাচাই, গেজেট উৎস ও রাষ্ট্রীয় পরিধি",
            "profileAssessmentSubtitle": "আপনার প্রোফাইলের ওপর ভিত্তি করে ব্যক্তিগতকৃত মূল্যায়ন",
            "creditFacility": "ঋণ সুবিধা",
            "noIncomeLimit": "কোনো বাধ্যতামূলক আয়সীমা নেই",
            "standardMarginMoney": "প্রকল্প ব্যয়ের ৫% - ১০%",
            "noCollateral": "কোনো জামানতের প্রয়োজন নেই (CGTMSE গ্যারান্টি)",
            "bankAssisted": "চ্যানেল অংশীদার / ব্যাংক সহায়ক",
            "directOnlinePortal": "সরাসরি অনলাইন পোর্টাল",
            "channelPartner": "চ্যানেল অংশীদার / সংস্থা",
            "noCreditWelfare": "না — অনুদান / কল্যাণমূলক প্রকল্প"
        }
    },
    "ta": {
        "common": {
            "status": "நிலை",
            "view": "பார்வை",
            "filter": "வடிகட்டி",
            "official": "அதிகாரப்பூர்வ",
            "prev": "முந்தைய",
            "verified": "சரிபார்க்கப்பட்டது",
            "viewAll": "அனைத்தையும் காண்க",
            "warning": "எச்சரிக்கை",
            "yes": "ஆம்",
            "no": "இல்லை"
        },
        "compare": {
            "applyOfficial": "அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்கவும்",
            "benefitSummary": "உதவி அமைப்பு",
            "browseSchemes": "திட்டங்களை உலாவுக",
            "calculateEmi": "இஎம்ஐ கணக்கிடுக",
            "calculatorAction": "கால்குலேட்டர் நடவடிக்கை",
            "documentsList": "தேவையான ஆவணங்கள்",
            "eligibilityStatus": "தகுதி நிலை",
            "eligible": "✓ தகுதியுடையவர்",
            "financialAssistance": "நிதி உதவி மற்றும் கடன் விதிமுறைகள்",
            "findPartners": "அங்கீகரிக்கப்பட்ட கூட்டாளர்களைக் கண்டறியவும்",
            "geographicCoverage": "புவியியல் வரம்பு",
            "incomeLimit": "வருமான வரம்பு",
            "interestRate": "வட்டி விகிதம்",
            "loanAvailable": "கடன் வசதி உள்ளது",
            "mandatoryDocuments": "கட்டாய ஆவணங்கள்",
            "maxLoan": "அதிகபட்ச கடன் தொகை",
            "ministry": "அமைச்சகம் / துறை",
            "moratorium": "தவணை ஒத்திவைப்பு காலம்",
            "occupation": "தொழில் / துறை",
            "officialSource": "அதிகாரப்பூர்வ ஆதாரம்",
            "remove": "நீக்குக",
            "repaymentTenure": "திருப்பிச் செலுத்தும் காலம்",
            "requiredDocs": "தேவையான ஆவணங்கள்",
            "schemeOverview": "திட்டத்தின் கண்ணோட்டம்",
            "schemePurpose": "நோக்கம் மற்றும் பலன்கள்",
            "schemeType": "திட்ட வகை",
            "secApplication": "விண்ணப்பம் மற்றும் அணுகல் வழி",
            "secDocuments": "ஆவணங்கள் மற்றும் சான்றுகள்",
            "secEligibility": "தகுதி வரம்புகள்",
            "secFinancial": "நிதி உதவி மற்றும் கடன் விதிமுறைகள்",
            "secOverview": "திட்ட கண்ணோட்டம் அட்டை",
            "secVerification": "அரசு சரிபார்ப்பு மற்றும் வரம்பு",
            "socialCategory": "சமூகப் பிரிவு மற்றும் பாலினம்",
            "subsidy": "மானியம் / உதவித்தொகை",
            "tenure": "திருப்பிச் செலுத்தும் காலம்",
            "title": "திட்டங்களை ஒப்பிடுக",
            "viewDetails": "விவரங்களைக் காண்க",
            "govVerification": "அரசு சரிபார்ப்பு",
            "lastVerified": "கடைசியாக சரிபார்க்கப்பட்ட தேதி",
            "notApplicable": "பொருந்தாது",
            "notSpecified": "அரசு ஆவணங்களில் குறிப்பிடப்படவில்லை",
            "marginMoney": "பயனாளி பங்கு",
            "collateral": "பிணையத் தேவை",
            "applicationMode": "விண்ணப்ப முறை",
            "applicationRoute": "விண்ணப்ப வழி",
            "officialPortal": "அதிகாரப்பூர்வ போர்டல்",
            "channelAgency": "செயல்படுத்தும் நிறுவனம்",
            "highestStated": "அதிகபட்சமாக குறிப்பிடப்பட்டது",
            "lowestStated": "குறைந்தபட்ச வட்டி விகிதம்",
            "secOverviewSubtitle": "அடிப்படை அமைப்பு, அமைச்சகம் மற்றும் புவியியல் பகுதி",
            "secEligibilitySubtitle": "வயது, வருமானம், சமூகப் பிரிவு மற்றும் தொழில்",
            "secFinancialSubtitle": "கடன் உச்சவரம்பு, வட்டி விகிதம் மற்றும் மானியம்",
            "secDocumentsSubtitle": "கட்டாய ஆவணங்கள் மற்றும் சான்றிதழ்கள்",
            "secApplicationSubtitle": "விண்ணப்ப செயல்முறை மற்றும் உதவி மையம்",
            "secVerificationSubtitle": "அரசு சரிபார்ப்பு மற்றும் மாநில வரம்பு",
            "profileAssessmentSubtitle": "உங்கள் விவரங்கள் அடிப்படையிலான தனிப்பயனாக்கப்பட்ட மதிப்பீடு",
            "creditFacility": "கடன் வசதி",
            "noIncomeLimit": "கட்டாய வருமான வரம்பு இல்லை",
            "standardMarginMoney": "திட்டச் செலவில் 5% - 10%",
            "noCollateral": "பிணையம் தேவையில்லை (CGTMSE உத்தரவாதம்)",
            "bankAssisted": "கூட்டாளர் / வங்கி உதவி",
            "directOnlinePortal": "நேரடி ஆன்லைன் போர்டல்",
            "channelPartner": "சேனல் கூட்டாளர் / நிறுவனம்",
            "noCreditWelfare": "இல்லை — மானியம் / நலத்திட்டம்"
        }
    },
    "te": {
        "common": {
            "status": "స్థితి",
            "view": "చూడండి",
            "filter": "ఫిల్టర్",
            "official": "అధికారిక",
            "prev": "మునుపటి",
            "verified": "ధృవీకరించబడింది",
            "viewAll": "అన్నీ చూడండి",
            "warning": "హెచ్చరిక",
            "yes": "అవును",
            "no": "కాదు"
        },
        "compare": {
            "applyOfficial": "అధికారిక పోర్టల్‌లో దరఖాస్తు చేసుకోండి",
            "benefitSummary": "సహాయక నిర్మాణం",
            "browseSchemes": "పథకాలను అన్వేషించండి",
            "calculateEmi": "ఇఎంఐ లెక్కించండి",
            "calculatorAction": "కాలిక్యులేటర్ చర్య",
            "documentsList": "అవసరమైన పత్రాలు",
            "eligibilityStatus": "అర్హత స్థితి",
            "eligible": "✓ అర్హులు",
            "financialAssistance": "ఆర్థిక సహాయం మరియు రుణ నిబంధనలు",
            "findPartners": "అధికారిక భాగస్వాములను కనుగొనండి",
            "geographicCoverage": "భౌగోళిక పరిధి",
            "incomeLimit": "ఆదాయ పరిమితి",
            "interestRate": "వడ్డీ రేటు",
            "loanAvailable": "రుణ సదుపాయం ఉంది",
            "mandatoryDocuments": "తప్పనిసరి పత్రాలు",
            "maxLoan": "గరిష్ట రుణ మొత్తం",
            "ministry": "మంత్రిత్వ శాఖ / విభాగం",
            "moratorium": "మొరటోరియం కాలం",
            "occupation": "వృత్తి / రంగం",
            "officialSource": "అధికారిక మూలం",
            "remove": "తొలగించు",
            "repaymentTenure": "తిరిగి చెల్లించే వ్యవధి",
            "requiredDocs": "అవసరమైన పత్రాలు",
            "schemeOverview": "పథకం స్థూలదృష్టి",
            "schemePurpose": "ఉద్దేశ్యం మరియు ప్రయోజనాలు",
            "schemeType": "పథకం రకం",
            "secApplication": "దరఖాస్తు మరియు ప్రవేశ మార్గం",
            "secDocuments": "పత్రాలు మరియు ధృవీకరణలు",
            "secEligibility": "అర్హత ప్రమాణాలు",
            "secFinancial": "ఆర్థిక సహాయం మరియు రుణ నిబంధనలు",
            "secOverview": "పథకం అవలోకన కార్డు",
            "secVerification": "ప్రభుత్వ ధృవీకరణ మరియు పరిధి",
            "socialCategory": "సామాజిక వర్గం మరియు లింగం",
            "subsidy": "సబ్సిడీ / గ్రాంట్",
            "tenure": "తిరిగి చెల్లించే కాలం",
            "title": "పథకాలను పోల్చండి",
            "viewDetails": "వివరాలు చూడండి",
            "govVerification": "ప్రభుత్వ ధృవీకరణ",
            "lastVerified": "చివరిగా ధృవీకరించిన తేదీ",
            "notApplicable": "వర్తించదు",
            "notSpecified": "ప్రభుత్వ పత్రాలలో పేర్కొనబడలేదు",
            "marginMoney": "లబ్ధిదారుడి వాటా",
            "collateral": "హామీ అవసరం",
            "applicationMode": "దరఖాస్తు విధానం",
            "applicationRoute": "దరఖాస్తు మార్గం",
            "officialPortal": "అధికారిక పోర్టల్",
            "channelAgency": "అమలు చేసే ఏజెన్సీ",
            "highestStated": "గరిష్టంగా పేర్కొనబడింది",
            "lowestStated": "కనిష్ట వడ్డీ రేటు",
            "secOverviewSubtitle": "ప్రాథమిక నిర్మాణం, మంత్రిత్వ శాఖ మరియు భౌగోళిక పరిధి",
            "secEligibilitySubtitle": "వయస్సు, ఆదాయం, సామాజిక వర్గం మరియు వృత్తి",
            "secFinancialSubtitle": "రుణ పరిమితి, వడ్డీ రేటు మరియు సబ్సిడీ",
            "secDocumentsSubtitle": "తప్పనిసరి పత్రాలు మరియు సర్టిఫికెట్లు",
            "secApplicationSubtitle": "దరఖాస్తు ప్రక్రియ మరియు సహాయ కేంద్రం",
            "secVerificationSubtitle": "ప్రభుత్వ ధృవీకరణ మరియు రాష్ట్ర పరిధి",
            "profileAssessmentSubtitle": "మీ వివరాల ఆధారంగా అర్హత మూల్యాంకనం",
            "creditFacility": "రుణ సదుపాయం",
            "noIncomeLimit": "తప్పనిసరి ఆదాయ పరిమితి లేదు",
            "standardMarginMoney": "ప్రాజెక్ట్ ఖర్చులో 5% - 10%",
            "noCollateral": "హామీ అవసరం లేదు (CGTMSE గ్యారెంటీ)",
            "bankAssisted": "ఛానల్ భాగస్వామి / బ్యాంక్ సహాయం",
            "directOnlinePortal": "ప్రత్యక్ష ఆన్‌లైన్ పోర్టల్",
            "channelPartner": "ఛానల్ భాగస్వామి / ఏజెన్సీ",
            "noCreditWelfare": "కాదు — గ్రాంట్ / సబ్సిడీ / సంక్షేమ పథకం"
        }
    },
    "gu": {
        "common": {
            "status": "સ્થિતિ",
            "view": "જુઓ",
            "filter": "ફિલ્ટર",
            "official": "સત્તાવાર",
            "prev": "પાછલું",
            "verified": "ચકાસાયેલ",
            "viewAll": "બધું જુઓ",
            "warning": "ચેતવણી",
            "yes": "હા",
            "no": "ના"
        },
        "compare": {
            "applyOfficial": "સત્તાવાર પોર્ટલ પર અરજી કરો",
            "benefitSummary": "સહાયતા માળખું",
            "browseSchemes": "યોજનાઓ શોધો",
            "calculateEmi": "ઈએમઆઈ ગણો",
            "calculatorAction": "કેલ્ક્યુલેટર",
            "documentsList": "જરૂરી દસ્તાવેજો",
            "eligibilityStatus": "પાત્રતા સ્થિતિ",
            "eligible": "✓ પાત્ર",
            "financialAssistance": "નાણાકીય સહાય અને લોનની શરતો",
            "findPartners": "અધિકૃત પાર્ટનર શોધો",
            "geographicCoverage": "ભૌગોલિક વ્યાપ",
            "incomeLimit": "આવક મર્યાદા",
            "interestRate": "વ્યાજ દર",
            "loanAvailable": "લોન સુવિધા ઉપલબ્ધ",
            "mandatoryDocuments": "ફરજિયાત દસ્તાવેજો",
            "maxLoan": "મહત્તમ લોન રકમ",
            "ministry": "મંત્રાલય / વિભાગ",
            "moratorium": "મોરેટોરિયમ સમયગાળો",
            "occupation": "વ્યવસાય / ક્ષેત્ર",
            "officialSource": "સત્તાવાર સ્ત્રોત",
            "remove": "દૂર કરો",
            "repaymentTenure": "ચુકવણીનો સમયગાળો",
            "requiredDocs": "જરૂરી દસ્તાવેજો",
            "schemeOverview": "યોજના વિહંગાવલોકન",
            "schemePurpose": "હેતુ અને લાભો",
            "schemeType": "યોજનાનો પ્રકાર",
            "secApplication": "અરજી અને પહોંચવાનો માર્ગ",
            "secDocuments": "દસ્તાવેજો અને પુરાવા",
            "secEligibility": "પાત્રતા માપદંડ",
            "secFinancial": "નાણાકીય સહાય અને લોનની શરતો",
            "secOverview": "યોજના વિહંગાવલોકન કાર્ડ",
            "secVerification": "સરકારી ચકાસણી અને વ્યાપ",
            "socialCategory": "સામાજિક વર્ગ અને જાતિ",
            "subsidy": "સબસિડી / ગ્રાન્ટ",
            "tenure": "ચુકવણી સમયગાળો",
            "title": "યોજનાઓની સરખામણી કરો",
            "viewDetails": "વિગતો જુઓ",
            "govVerification": "સરકારી ચકાસણી",
            "lastVerified": "છેલ્લી ચકાસણી તારીખ",
            "notApplicable": "લાગુ પડતું નથી",
            "notSpecified": "સરકારી દસ્તાવેજોમાં ઉલ્લેખ નથી",
            "marginMoney": "લાભાર્થીનો હિસ્સો",
            "collateral": "જામીનગીરીની જરૂરિયાત",
            "applicationMode": "અરજી કરવાની રીત",
            "applicationRoute": "અરજીનો માર્ગ",
            "officialPortal": "સત્તાવાર પોર્ટલ",
            "channelAgency": "અમલીકરણ એજન્સી",
            "highestStated": "મહત્તમ જણાવેલ",
            "lowestStated": "ન્યૂનતમ વ્યાજ દર",
            "secOverviewSubtitle": "મૂળ માળખું, મંત્રાલય અને ભૌગોલિક વિસ્તાર",
            "secEligibilitySubtitle": "ઉંમર, આવક, સામાજિક વર્ગ અને વ્યવસાય",
            "secFinancialSubtitle": "લોન મર્યાદા, વ્યાજ દર અને સબસિડી",
            "secDocumentsSubtitle": "ફરજિયાત દસ્તાવેજો અને પ્રમાણપત્રો",
            "secApplicationSubtitle": "અરજી પ્રક્રિયા અને સહાય કેન્દ્ર",
            "secVerificationSubtitle": "સરકારી ચકાસણી અને રાજ્ય વ્યાપ",
            "profileAssessmentSubtitle": "તમારી પ્રોફાઇલ આધારિત પાત્રતા મૂલ્યાંકન",
            "creditFacility": "લોન સુવિધા",
            "noIncomeLimit": "કોઈ ફરજિયાત મર્યાદા નથી",
            "standardMarginMoney": "પ્રોજેક્ટ ખર્ચના 5% - 10%",
            "noCollateral": "કોઈ જામીનગીરી જરૂરી નથી (CGTMSE ગેરંટી)",
            "bankAssisted": "ચેનલ પાર્ટનર / બેંક સહાયતા",
            "directOnlinePortal": "સીધું ઓનલાઇન પોર્ટલ",
            "channelPartner": "ચેનલ પાર્ટનર / એજન્સી",
            "noCreditWelfare": "ના — ગ્રાન્ટ / સબસિડી / કલ્યાણકારી યોજના"
        }
    },
    "kn": {
        "common": {
            "status": "ಸ್ಥಿತಿ",
            "view": "ವೀಕ್ಷಿಸಿ",
            "filter": "ಫಿಲ್ಟರ್",
            "official": "ಅಧಿಕೃತ",
            "prev": "ಹಿಂದಿನ",
            "verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
            "viewAll": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
            "warning": "ಎಚ್ಚರಿಕೆ",
            "yes": "ಹೌದು",
            "no": "ಇಲ್ಲ"
        },
        "compare": {
            "applyOfficial": "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
            "benefitSummary": "ಸಹಾಯ ರಚನೆ",
            "browseSchemes": "ಯೋಜನೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
            "calculateEmi": "ಇಎಂಐ ಲೆಕ್ಕಹಾಕಿ",
            "calculatorAction": "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಕ್ರಿಯೆ",
            "documentsList": "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
            "eligibilityStatus": "ಅರ್ಹತಾ ಸ್ಥಿತಿ",
            "eligible": "✓ ಅರ್ಹರು",
            "financialAssistance": "ಹಣಕಾಸು ನೆರವು ಮತ್ತು ಸಾಲದ ನಿಯಮಗಳು",
            "findPartners": "ಅಧಿಕೃತ ಪಾಲುದಾರರನ್ನು ಹುಡುಕಿ",
            "geographicCoverage": "ಭೌಗೋಳಿಕ ವ್ಯಾಪ್ತಿ",
            "incomeLimit": "ಆದಾಯ ಮಿತಿ",
            "interestRate": "ಬಡ್ಡಿ ದರ",
            "loanAvailable": "ಸಾಲದ ಸೌಲಭ್ಯ ಲಭ್ಯವಿದೆ",
            "mandatoryDocuments": "ಕಡ್ಡಾಯ ದಾಖಲೆಗಳು",
            "maxLoan": "ಗರಿಷ್ಠ ಸಾಲದ ಮೊತ್ತ",
            "ministry": "ಸಚಿವಾಲಯ / ಇಲಾಖೆ",
            "moratorium": "ಮೊರಟೋರಿಯಂ ಅವಧಿ",
            "occupation": "ವೃತ್ತಿ / ಕ್ಷೇತ್ರ",
            "officialSource": "ಅಧಿಕೃತ ಮೂಲ",
            "remove": "ತೆಗೆದುಹಾಕಿ",
            "repaymentTenure": "ಮರುಪಾವತಿ ಅವಧಿ",
            "requiredDocs": "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
            "schemeOverview": "ಯೋಜನೆಯ ಅವಲೋಕನ",
            "schemePurpose": "ಉದ್ದೇಶ ಮತ್ತು ಪ್ರಯೋಜನಗಳು",
            "schemeType": "ಯೋಜನೆಯ ಪ್ರಕಾರ",
            "secApplication": "ಅರ್ಜಿ ಮತ್ತು ಪ್ರವೇಶ ಮಾರ್ಗ",
            "secDocuments": "ದಾಖಲೆಗಳು ಮತ್ತು ಪುರಾವೆಗಳು",
            "secEligibility": "ಅರ್ಹತಾ ಮಾನದಂಡಗಳು",
            "secFinancial": "ಹಣಕಾಸು ನೆರವು ಮತ್ತು ಸಾಲದ ನಿಯಮಗಳು",
            "secOverview": "ಯೋಜನೆ ಅವಲೋಕನ ಕಾರ್ಡ್",
            "secVerification": "ಸರ್ಕಾರಿ ಪರಿಶೀಲನೆ ಮತ್ತು ವ್ಯಾಪ್ತಿ",
            "socialCategory": "ಸಾಮಾಜಿಕ ವರ್ಗ ಮತ್ತು ಲಿಂಗ",
            "subsidy": "ಸಬ್ಸಿಡಿ / ಅನುದಾನ",
            "tenure": "ಮರುಪಾವತಿ ಅವಧಿ",
            "title": "ಯೋಜನೆಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ",
            "viewDetails": "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
            "govVerification": "ಸರ್ಕಾರಿ ಪರಿಶೀಲನೆ",
            "lastVerified": "ಕೊನೆಯ ಪರಿಶೀಲನೆ ದಿನಾಂಕ",
            "notApplicable": "ಅನ್ವಯಿಸುವುದಿಲ್ಲ",
            "notSpecified": "ಸರ್ಕಾರಿ ದಾಖಲೆಗಳಲ್ಲಿ ನಮೂದಿಸಿಲ್ಲ",
            "marginMoney": "ಫಲಾನುಭವಿಯ ಪಾಲು",
            "collateral": "ಅಡಮಾನದ ಅವಶ್ಯಕತೆ",
            "applicationMode": "ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ವಿಧಾನ",
            "applicationRoute": "ಅರ್ಜಿ ಮಾರ್ಗ",
            "officialPortal": "ಅಧಿಕೃತ ಪೋರ್ಟಲ್",
            "channelAgency": "ಅನುಷ್ಠಾನ ಸಂಸ್ಥೆ",
            "highestStated": "ಗರಿಷ್ಠ ನಮೂದಿಸಲಾಗಿದೆ",
            "lowestStated": "ಕನಿಷ್ಠ ಬಡ್ಡಿ ದರ",
            "secOverviewSubtitle": "ಮೂಲ ರಚನೆ, ಸಚಿವಾಲಯ ಮತ್ತು ಭೌಗೋಳಿಕ ವ್ಯಾಪ್ತಿ",
            "secEligibilitySubtitle": "ವಯಸ್ಸು, ಆದಾಯ, ಸಾಮಾಜಿಕ ವರ್ಗ ಮತ್ತು ವೃತ್ತಿ",
            "secFinancialSubtitle": "ಸಾಲದ ಮಿತಿ, ಬಡ್ಡಿ ದರ ಮತ್ತು ಸಬ್ಸಿಡಿ",
            "secDocumentsSubtitle": "ಕಡ್ಡಾಯ ದಾಖಲೆಗಳು ಮತ್ತು ಪ್ರಮಾಣಪತ್ರಗಳು",
            "secApplicationSubtitle": "ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆ ಮತ್ತು ಸಹಾಯ ಕೇಂದ್ರ",
            "secVerificationSubtitle": "ಸರ್ಕಾರಿ ಪರಿಶೀಲನೆ ಮತ್ತು ರಾಜ್ಯ ವ್ಯಾಪ್ತಿ",
            "profileAssessmentSubtitle": "ನಿಮ್ಮ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ ಅರ್ಹತಾ ಮೌಲ್ಯಮಾಪನ",
            "creditFacility": "ಸಾಲದ ಸೌಲಭ್ಯ",
            "noIncomeLimit": "ಯಾವುದೇ ಕಡ್ಡಾಯ ಆದಾಯ ಮಿತಿಯಿಲ್ಲ",
            "standardMarginMoney": "ಯೋಜನಾ ವೆಚ್ಚದ 5% - 10%",
            "noCollateral": "ಅಡಮಾನ ಅಗತ್ಯವಿಲ್ಲ (CGTMSE ಗ್ಯಾರಂಟಿ)",
            "bankAssisted": "ಚಾನೆಲ್ ಪಾಲುದಾರ / ಬ್ಯಾಂಕ್ ನೆರವು",
            "directOnlinePortal": "ನೇರ ಆನ್‌ಲೈನ್ ಪೋರ್ಟಲ್",
            "channelPartner": "ಚಾನೆಲ್ ಪಾಲುದಾರ / ಸಂಸ್ಥೆ",
            "noCreditWelfare": "ಇಲ್ಲ — ಅನುದಾನ / ಸಬ್ಸಿಡಿ / ಕಲ್ಯಾಣ ಯೋಜನೆ"
        }
    },
    "ml": {
        "common": {
            "status": "നില",
            "view": "കാണുക",
            "filter": "ഫിൽട്ടർ",
            "official": "ഔദ്യോഗികം",
            "prev": "മുമ്പത്തെ",
            "verified": "സ്ഥിരീകരിച്ചു",
            "viewAll": "എല്ലാം കാണുക",
            "warning": "മുന്നറിയിപ്പ്",
            "yes": "അതെ",
            "no": "അല്ല"
        },
        "compare": {
            "applyOfficial": "ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷിക്കുക",
            "benefitSummary": "സഹായ ഘടന",
            "browseSchemes": "പദ്ധതികൾ ബ്രൗസ് ചെയ്യുക",
            "calculateEmi": "ഇഎംഐ കണക്കാക്കുക",
            "calculatorAction": "കാൽക്കുലേറ്റർ",
            "documentsList": "ആവശ്യമായ രേഖകൾ",
            "eligibilityStatus": "അർഹതാ നില",
            "eligible": "✓ അർഹതയുണ്ട്",
            "financialAssistance": "സാമ്പത്തിക സഹായവും വായ്പാ വ്യവസ്ഥകളും",
            "findPartners": "അംഗീകൃത പങ്കാളികളെ കണ്ടെത്തുക",
            "geographicCoverage": "ഭൂമിശാസ്ത്രപരമായ പരിധി",
            "incomeLimit": "വരുമാന പരിധി",
            "interestRate": "പലിശ നിരക്ക്",
            "loanAvailable": "വായ്പാ സൗകര്യം ലഭ്യമാണ്",
            "mandatoryDocuments": "നിർബന്ധിത രേഖകൾ",
            "maxLoan": "പരമാവധി വായ്പ തുക",
            "ministry": "മന്ത്രാലയം / വകുപ്പ്",
            "moratorium": "മൊറട്ടോറിയം കാലയളവ്",
            "occupation": "തൊഴിൽ / മേഖല",
            "officialSource": "ഔദ്യോഗിക ഉറവിടം",
            "remove": "നീക്കം ചെയ്യുക",
            "repaymentTenure": "തിരിച്ചടവ് കാലയളവ്",
            "requiredDocs": "ആവശ്യമായ രേഖകൾ",
            "schemeOverview": "പദ്ധതി അവലോകനം",
            "schemePurpose": "ലക്ഷ്യവും ആനുകൂല്യങ്ങളും",
            "schemeType": "പദ്ധതി തരം",
            "secApplication": "അപേക്ഷയും പ്രവേശന വഴിയും",
            "secDocuments": "രേഖകളും തെളിവുകളും",
            "secEligibility": "അർഹതാ മാനദണ്ഡങ്ങൾ",
            "secFinancial": "സാമ്പത്തിക സഹായവും വായ്പാ വ്യവസ്ഥകളും",
            "secOverview": "പദ്ധതി അവലോകന കാർഡ്",
            "secVerification": "സർക്കാർ സ്ഥിരീകരണവും പരിധിയും",
            "socialCategory": "സാമൂഹിക വിഭാഗവും ലിംഗഭേദവും",
            "subsidy": "സബ്‌സിഡി / ഗ്രാന്റ്",
            "tenure": "തിരിച്ചടവ് കാലാവധി",
            "title": "പദ്ധതികൾ താരതമ്യം ചെയ്യുക",
            "viewDetails": "വിശദാംശങ്ങൾ കാണുക",
            "govVerification": "സർക്കാർ സ്ഥിരീകരണം",
            "lastVerified": "അവസാനം പരിശോധിച്ച തീയതി",
            "notApplicable": "ബാധകമല്ല",
            "notSpecified": "ഔദ്യോഗിക രേഖകളിൽ വ്യക്തമാക്കിയിട്ടില്ല",
            "marginMoney": "ഗുണഭോക്തൃ വിഹിതം",
            "collateral": "ഈട് ആവശ്യകത",
            "applicationMode": "അപേക്ഷാരീതി",
            "applicationRoute": "അപേക്ഷാ വഴി",
            "officialPortal": "ഔദ്യോഗിക പോർട്ടൽ",
            "channelAgency": "നടത്തിപ്പ് ഏജൻസി",
            "highestStated": "പരമാവധി രേഖപ്പെടുത്തിയത്",
            "lowestStated": "ഏറ്റവും കുറഞ്ഞ പലിശ നിരക്ക്",
            "secOverviewSubtitle": "അടിസ്ഥാന ഘടന, മന്ത്രാലയം, ഭൂമിശാസ്ത്ര പരിധി",
            "secEligibilitySubtitle": "പ്രായം, വരുമാനം, സാമൂഹിക വിഭാഗം, തൊഴിൽ",
            "secFinancialSubtitle": "വായ്പാ പരിധി, പലിശ നിരക്ക്, സബ്‌സിഡി",
            "secDocumentsSubtitle": "നിർബന്ധിത രേഖകളും സർട്ടിഫിക്കറ്റുകളും",
            "secApplicationSubtitle": "അപേക്ഷാ നടപടികളും സഹായ കേന്ദ്രങ്ങളും",
            "secVerificationSubtitle": "സർക്കാർ പരിശോധനയും സംസ്ഥാന പരിധിയും",
            "profileAssessmentSubtitle": "നിങ്ങളുടെ വിവരങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ള വിലയിരുത്തൽ",
            "creditFacility": "വായ്പാ സൗകര്യം",
            "noIncomeLimit": "നിർബന്ധിത വരുമാന പരിധിയില്ല",
            "standardMarginMoney": "പദ്ധതി ചെലവിന്റെ 5% - 10%",
            "noCollateral": "ഈട് ആവശ്യമില്ല (CGTMSE ഗ്യാരണ്ടി)",
            "bankAssisted": "ചാനൽ പങ്കാളി / ബാങ്ക് സഹായം",
            "directOnlinePortal": "നേരിട്ടുള്ള ഓൺലൈൻ പോർട്ടൽ",
            "channelPartner": "ചാനൽ പങ്കാളി / ഏജൻസി",
            "noCreditWelfare": "അല്ല — ഗ്രാന്റ് / സബ്‌സിഡി / ക്ഷേമ പദ്ധതി"
        }
    },
    "pa": {
        "common": {
            "status": "ਸਥਿਤੀ",
            "view": "ਦੇਖੋ",
            "filter": "ਫਿਲਟਰ",
            "official": "ਅਧਿਕਾਰਤ",
            "prev": "ਪਿਛਲਾ",
            "verified": "ਪ੍ਰਮਾਣਿਤ",
            "viewAll": "ਸਾਰੇ ਦੇਖੋ",
            "warning": "ਚੇਤਾਵਨੀ",
            "yes": "ਹਾਂ",
            "no": "ਨਹੀਂ"
        },
        "compare": {
            "applyOfficial": "ਅਧਿਕਾਰਤ ਪੋਰਟਲ 'ਤੇ ਅਰਜ਼ੀ ਦਿਓ",
            "benefitSummary": "ਸਹਾਇਤਾ ਢਾਂਚਾ",
            "browseSchemes": "ਸਕੀਮਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
            "calculateEmi": "ਈਐਮਆਈ ਗਣਨਾ ਕਰੋ",
            "calculatorAction": "ਕੈਲਕੁਲੇਟਰ ਕਾਰਵਾਈ",
            "documentsList": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
            "eligibilityStatus": "ਯੋਗਤਾ ਸਥਿਤੀ",
            "eligible": "✓ ਯੋਗ",
            "financialAssistance": "ਵਿੱਤੀ ਸਹਾਇਤਾ ਅਤੇ ਕਰਜ਼ੇ ਦੀਆਂ ਸ਼ਰਤਾਂ",
            "findPartners": "ਅਧਿਕਾਰਤ ਭਾਈਵਾਲ ਲੱਭੋ",
            "geographicCoverage": "ਭੂਗੋਲਿਕ ਦਾਇਰਾ",
            "incomeLimit": "ਆਮਦਨ ਸੀਮਾ",
            "interestRate": "ਵਿਆਜ ਦਰ",
            "loanAvailable": "ਕਰਜ਼ਾ ਸਹੂਲਤ ਉਪਲਬਧ",
            "mandatoryDocuments": "ਲਾਜ਼ਮੀ ਦਸਤਾਵੇਜ਼",
            "maxLoan": "ਵੱਧ ਤੋਂ ਵੱਧ ਕਰਜ਼ਾ ਰਕਮ",
            "ministry": "ਮੰਤਰਾਲਾ / ਵਿਭਾਗ",
            "moratorium": "ਮੋਰਾਟੋਰੀਅਮ ਮਿਆਦ",
            "occupation": "ਕਿੱਤਾ / ਖੇਤਰ",
            "officialSource": "ਅਧਿਕਾਰਤ ਸਰੋਤ",
            "remove": "ਹਟਾਓ",
            "repaymentTenure": "ਮੋੜਨ ਦੀ ਮਿਆਦ",
            "requiredDocs": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
            "schemeOverview": "ਸਕੀਮ ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
            "schemePurpose": "ਉਦੇਸ਼ ਅਤੇ ਲਾਭ",
            "schemeType": "ਸਕੀਮ ਦੀ ਕਿਸਮ",
            "secApplication": "ਅਰਜ਼ੀ ਅਤੇ ਪਹੁੰਚ ਰਸਤਾ",
            "secDocuments": "ਦਸਤਾਵੇਜ਼ ਅਤੇ ਸਬੂਤ",
            "secEligibility": "ਯੋਗਤਾ ਮਾਪਦੰਡ",
            "secFinancial": "ਵਿੱਤੀ ਸਹਾਇਤਾ ਅਤੇ ਕਰਜ਼ੇ ਦੀਆਂ ਸ਼ਰਤਾਂ",
            "secOverview": "ਸਕੀਮ ਸੰਖੇਪ ਕਾਰਡ",
            "secVerification": "ਸਰਕਾਰੀ ਪ੍ਰਮਾਣੀਕਰਨ ਅਤੇ ਦਾਇਰਾ",
            "socialCategory": "ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ ਅਤੇ ਲਿੰਗ",
            "subsidy": "ਸਬਸਿਡੀ / ਗ੍ਰਾਂਟ",
            "tenure": "ਮੋੜਨ ਦੀ ਮਿਆਦ",
            "title": "ਸਕੀਮਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ",
            "viewDetails": "ਵੇਰਵੇ ਦੇਖੋ",
            "govVerification": "ਸਰਕਾਰੀ ਪ੍ਰਮਾਣੀਕਰਨ",
            "lastVerified": "ਆਖਰੀ ਪ੍ਰਮਾਣਿਤ ਮਿਤੀ",
            "notApplicable": "ਲਾਗੂ ਨਹੀਂ",
            "notSpecified": "ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼ਾਂ ਵਿੱਚ ਦਰਜ ਨਹੀਂ",
            "marginMoney": "ਲਾਭਪਾਤਰੀ ਦਾ ਹਿੱਸਾ",
            "collateral": "ਜ਼ਮਾਨਤ ਦੀ ਲੋੜ",
            "applicationMode": "ਅਰਜ਼ੀ ਦਾ ਤਰੀਕਾ",
            "applicationRoute": "ਅਰਜ਼ੀ ਰਸਤਾ",
            "officialPortal": "ਅਧਿਕਾਰਤ ਪੋਰਟਲ",
            "channelAgency": "ਲਾਗੂ ਕਰਨ ਵਾਲੀ ਏਜੰਸੀ",
            "highestStated": "ਵੱਧ ਤੋਂ ਵੱਧ ਦਰਜ",
            "lowestStated": "ਘੱਟੋ-ਘੱਟ ਵਿਆਜ ਦਰ",
            "secOverviewSubtitle": "ਬੁਨਿਆਦੀ ਢਾਂਚਾ, ਮੰਤਰਾਲਾ ਅਤੇ ਭੂਗੋਲਿਕ ਖੇਤਰ",
            "secEligibilitySubtitle": "ਉਮਰ, ਆਮਦਨ, ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ ਅਤੇ ਕਿੱਤਾ",
            "secFinancialSubtitle": "ਕਰਜ਼ਾ ਸੀਮਾ, ਵਿਆਜ ਦਰ ਅਤੇ ਸਬਸਿਡੀ",
            "secDocumentsSubtitle": "ਲਾਜ਼ਮੀ ਦਸਤਾਵੇਜ਼ ਅਤੇ ਸਰਟੀਫਿਕੇਟ",
            "secApplicationSubtitle": "ਅਰਜ਼ੀ ਪ੍ਰਕਿਰਿਆ ਅਤੇ ਸਹਾਇਤਾ ਕੇਂਦਰ",
            "secVerificationSubtitle": "ਸਰਕਾਰੀ ਪ੍ਰਮਾਣੀਕਰਨ ਅਤੇ ਰਾਜ ਦਾਇਰਾ",
            "profileAssessmentSubtitle": "ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਅਨੁਸਾਰ ਯੋਗਤਾ ਮੁਲਾਂਕਣ",
            "creditFacility": "ਕਰਜ਼ਾ ਸਹੂਲਤ",
            "noIncomeLimit": "ਕੋਈ ਲਾਜ਼ਮੀ ਆਮਦਨ ਸੀਮਾ ਨਹੀਂ",
            "standardMarginMoney": "ਪ੍ਰੋਜੈਕਟ ਲਾਗਤ ਦਾ 5% - 10%",
            "noCollateral": "ਕਿਸੇ ਜ਼ਮਾਨਤ ਦੀ ਲੋੜ ਨਹੀਂ (CGTMSE ਗਾਰੰਟੀ)",
            "bankAssisted": "ਚੈਨਲ ਸਾਥੀ / ਬੈਂਕ ਸਹਾਇਤਾ",
            "directOnlinePortal": "ਸਿੱਧਾ ਆਨਲਾਈਨ ਪੋਰਟਲ",
            "channelPartner": "ਚੈਨਲ ਸਾਥੀ / ਏਜੰਸੀ",
            "noCreditWelfare": "ਨਹੀਂ — ਗ੍ਰਾਂਟ / ਸਬਸਿਡੀ / ਭਲਾਈ ਸਕੀਮ"
        }
    },
    "or": {
        "common": {
            "status": "ସ୍ଥିତି",
            "view": "ଦେଖନ୍ତୁ",
            "filter": "ଫିଲ୍ଟର",
            "official": "ସରକାରୀ",
            "prev": "ପୂର୍ବ",
            "verified": "ପ୍ରମାଣିତ",
            "viewAll": "ସମସ୍ତ ଦେଖନ୍ତୁ",
            "warning": "ଚେତାବନୀ",
            "yes": "ହଁ",
            "no": "ନା"
        },
        "compare": {
            "applyOfficial": "ସରକାରୀ ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ",
            "benefitSummary": "ସହାୟତା ଢାଞ୍ଚା",
            "browseSchemes": "ଯୋଜନା ବ୍ରାଉଜ୍ କରନ୍ତୁ",
            "calculateEmi": "ଇଏମଆଇ ଗଣନା କରନ୍ତୁ",
            "calculatorAction": "କାଲକୁଲେଟର",
            "documentsList": "ଆବଶ୍ୟକ ଦସ୍ତାବିଜ",
            "eligibilityStatus": "ଯୋଗ୍ୟତା ସ୍ଥିତି",
            "eligible": "✓ ଯୋଗ୍ୟ",
            "financialAssistance": "ଆର୍ଥିକ ସହାୟତା ଏବଂ ଋଣ ସର୍ତ୍ତାବଳୀ",
            "findPartners": "ଅଧିକୃତ ଅଂଶୀଦାର ଖୋଜନ୍ତୁ",
            "geographicCoverage": "ଭୌଗୋଳିକ ପରିସର",
            "incomeLimit": "ଆୟ ସୀମା",
            "interestRate": "ସୁଧ ହାର",
            "loanAvailable": "ଋଣ ସୁବିଧା ଉପଲବ୍ଧ",
            "mandatoryDocuments": "ବାଧ୍ୟତାମୂଳକ ଦସ୍ତାବିଜ",
            "maxLoan": "ସର୍ବାଧିକ ଋଣ ରାଶି",
            "ministry": "ମନ୍ତ୍ରଣାଳୟ / ବିଭାଗ",
            "moratorium": "ମୋରେଟୋରିୟମ୍ ଅବଧି",
            "occupation": "ବୃତ୍ତି / କ୍ଷେତ୍ର",
            "officialSource": "ସରକାରୀ ସୂତ୍ର",
            "remove": "ହଟାନ୍ତୁ",
            "repaymentTenure": "ପରିଶୋଧ ଅବଧି",
            "requiredDocs": "ଆବଶ୍ୟକ ଦସ୍ତାବିଜ",
            "schemeOverview": "ଯୋଜନା ସାରାଂଶ",
            "schemePurpose": "ଉଦ୍ଦେଶ୍ୟ ଏବଂ ଲାଭ",
            "schemeType": "ଯୋଜନାର ପ୍ରକାର",
            "secApplication": "ଆବେଦନ ଏବଂ ପ୍ରବେଶ ମାର୍ଗ",
            "secDocuments": "ଦସ୍ତାବିଜ ଏବଂ ପ୍ରମାଣପତ୍ର",
            "secEligibility": "ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ",
            "secFinancial": "ଆର୍ଥିକ ସହାୟତା ଏବଂ ଋଣ ସର୍ତ୍ତାବଳୀ",
            "secOverview": "ଯୋଜନା ସାରାଂଶ କାର୍ଡ",
            "secVerification": "ସରକାରୀ ପ୍ରମାଣୀକରଣ ଏବଂ ପରିସର",
            "socialCategory": "ସାମାଜିକ ବର୍ଗ ଏବଂ ଲିଙ୍ଗ",
            "subsidy": "ସବସିଡି / ଅନୁଦାନ",
            "tenure": "ପରିଶୋଧ ଅବଧି",
            "title": "ଯୋଜନାଗୁଡିକର ତୁଳନା କରନ୍ତୁ",
            "viewDetails": "ବିବରଣୀ ଦେଖନ୍ତୁ",
            "govVerification": "ସରକାରୀ ପ୍ରମାଣୀକରଣ",
            "lastVerified": "ଶେଷ ଯାଞ୍ଚ ତାରିଖ",
            "notApplicable": "ପ୍ରଯୁଜ୍ୟ ନୁହେଁ",
            "notSpecified": "ସରକାରୀ ତଥ୍ୟରେ ଉଲ୍ଲେଖ ନାହିଁ",
            "marginMoney": "ହିତାଧିକାରୀଙ୍କ ଅଂଶ",
            "collateral": "ଜାମିନ ଆବଶ୍ୟକତା",
            "applicationMode": "ଆବେଦନ ପ୍ରଣାଳୀ",
            "applicationRoute": "ଆବେଦନ ମାର୍ଗ",
            "officialPortal": "ସରକାରୀ ପୋର୍ଟାଲ",
            "channelAgency": "କାର୍ଯ୍ୟକାରୀ ସଂସ୍ଥା",
            "highestStated": "ସର୍ବାଧିକ ଉଲ୍ଲେଖିତ",
            "lowestStated": "ସର୍ବନିମ୍ନ ସୁଧ ହାର",
            "secOverviewSubtitle": "ମୂଳ ଢାଞ୍ଚା, ମନ୍ତ୍ରଣାଳୟ ଏବଂ ଭୌଗୋଳିକ ପରିସର",
            "secEligibilitySubtitle": "ବୟସ, ଆୟ, ସାମାଜିକ ବର୍ଗ ଏବଂ ବୃତ୍ତି",
            "secFinancialSubtitle": "ଋଣ ସୀମା, ସୁଧ ହାର ଏବଂ ସବସିଡି",
            "secDocumentsSubtitle": "ବାଧ୍ୟତାମୂଳକ ଦସ୍ତାବିଜ ଏବଂ ପ୍ରମାଣପତ୍ର",
            "secApplicationSubtitle": "ଆବେଦନ ପ୍ରକ୍ରିୟା ଏବଂ ସହାୟତା କେନ୍ଦ୍ର",
            "secVerificationSubtitle": "ସରକାରୀ ଯାଞ୍ଚ ଏବଂ ରାଜ୍ୟ ପରିସର",
            "profileAssessmentSubtitle": "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଉପରେ ଆଧାରିତ ମୂଲ୍ୟାଙ୍କନ",
            "creditFacility": "ଋଣ ସୁବିଧା",
            "noIncomeLimit": "କୌଣସି ବାଧ୍ୟତାମୂଳକ ସୀମା ନାହିଁ",
            "standardMarginMoney": "ପ୍ରକଳ୍ପ ମୂଲ୍ୟର 5% - 10%",
            "noCollateral": "କୌଣସି ଜାମିନ ଆବଶ୍ୟକ ନାହିଁ (CGTMSE ଗ୍ୟାରେଣ୍ଟି)",
            "bankAssisted": "ଚ୍ୟାନେଲ ଅଂଶୀଦାର / ବ୍ୟାଙ୍କ ସହାୟତା",
            "directOnlinePortal": "ସିଧାସଳଖ ଅନଲାଇନ୍ ପୋର୍ଟାଲ୍",
            "channelPartner": "ଚ୍ୟାନେଲ ଅଂଶୀଦାର / ସଂସ୍ଥା",
            "noCreditWelfare": "ନା — ଅନୁଦାନ / ସବସିଡି / କଲ୍ୟାଣକାରୀ ଯୋଜନା"
        }
    },
    "as": {
        "common": {
            "status": "স্থিতি",
            "view": "চাওক",
            "filter": "ফিল্টাৰ",
            "official": "আনুষ্ঠানিক",
            "prev": "পূৰ্বৱৰ্তী",
            "verified": "প্ৰমাণিত",
            "viewAll": "সকলো চাওক",
            "warning": "সতৰ্কবাণী",
            "yes": "হয়",
            "no": "নহয়"
        },
        "compare": {
            "applyOfficial": "আনুষ্ঠানিক পৰ্টেলত আবেদন কৰক",
            "benefitSummary": "সাহায্য গাঁথনি",
            "browseSchemes": "আঁচনি চাওক",
            "calculateEmi": "ইএমআই হিচাপ কৰক",
            "calculatorAction": "কেলকুলেটৰ ব্যৱস্থা",
            "documentsList": "প্ৰয়োজনীয় নথি",
            "eligibilityStatus": "যোগ্যতাৰ স্থিতি",
            "eligible": "✓ যোগ্য",
            "financialAssistance": "বিত্তীয় সাহায্য আৰু ঋণৰ চৰ্তাৱলী",
            "findPartners": "অনুমোদিত অংশীদাৰ বিচাৰক",
            "geographicCoverage": "ভৌগোলিক পৰিসৰ",
            "incomeLimit": "আয়সীমা",
            "interestRate": "সুদৰ হাৰ",
            "loanAvailable": "ঋণৰ সুবিধা উপলব্ধ",
            "mandatoryDocuments": "বাধ্যতামূলক নথি",
            "maxLoan": "সৰ্বাধিক ঋণৰ পৰিমাণ",
            "ministry": "মন্ত্ৰালয় / বিভাগ",
            "moratorium": "মৰেটৰিয়ামৰ সময়সীমা",
            "occupation": "বৃত্তি / খণ্ড",
            "officialSource": "আনুষ্ঠানিক উৎস",
            "remove": "আঁতৰাওক",
            "repaymentTenure": "পৰিশোধৰ সময়সীমা",
            "requiredDocs": "প্ৰয়োজনীয় নথি",
            "schemeOverview": "আঁচনিৰ চমু বিৱৰণ",
            "schemePurpose": "উদ্দেশ্য আৰু সুবিধা",
            "schemeType": "আঁচনিৰ প্ৰকাৰ",
            "secApplication": "আবেদন আৰু প্ৰৱেশ পথ",
            "secDocuments": "নথিপত্ৰ আৰু প্ৰমাণ",
            "secEligibility": "যোগ্যতাৰ মাপকাঠী",
            "secFinancial": "বিত্তীয় সাহায্য আৰু ঋণৰ চৰ্তাৱলী",
            "secOverview": "আঁচনিৰ বিৱৰণ কাৰ্ড",
            "secVerification": "চৰকাৰী পৰীক্ষণ আৰু পৰিসৰ",
            "socialCategory": "সামাজিক শ্ৰেণী আৰু লিংগ",
            "subsidy": "ৰাজসাহায্য / অনুদান",
            "tenure": "পৰিশোধৰ সময়সীমা",
            "title": "আঁচনি তুলনা কৰক",
            "viewDetails": "বিৱৰণ চাওক",
            "govVerification": "চৰকাৰী পৰীক্ষণ",
            "lastVerified": "অন্তিম পৰীক্ষণৰ তাৰিখ",
            "notApplicable": "প্ৰযোজ্য নহয়",
            "notSpecified": "চৰকাৰী নথিত উল্লেখ নাই",
            "marginMoney": "হিতাধিকাৰীৰ অংশ",
            "collateral": "বন্ধকীৰ প্ৰয়োজনীয়তা",
            "applicationMode": "আবেদনৰ ধৰণ",
            "applicationRoute": "আবেদনৰ পথ",
            "officialPortal": "আনুষ্ঠানিক পৰ্টেল",
            "channelAgency": "কাৰ্যকৰী সংস্থা",
            "highestStated": "সৰ্বাধিক উল্লেখিত",
            "lowestStated": "নূন্যতম সুদৰ হাৰ",
            "secOverviewSubtitle": "মূল গাঁথনি, মন্ত্ৰালয় আৰু ভৌগোলিক পৰিসৰ",
            "secEligibilitySubtitle": "বয়স, আয়, সামাজিক শ্ৰেণী আৰু বৃত্তি",
            "secFinancialSubtitle": "ঋণৰ সীমা, সুদৰ হাৰ আৰু ৰাজসাহায্য",
            "secDocumentsSubtitle": "বাধ্যতামূলক নথি আৰু প্ৰমাণপত্ৰ",
            "secApplicationSubtitle": "আবেদন প্ৰক্ৰিয়া আৰু সাহায্য কেন্দ্ৰ",
            "secVerificationSubtitle": "চৰকাৰী তথ্য পৰীক্ষণ আৰু ৰাজ্যিক পৰিসৰ",
            "profileAssessmentSubtitle": "আপোনাৰ তথ্যৰ ওপৰত ভিত্তি কৰি মূল্যায়ন",
            "creditFacility": "ঋণৰ সুবিধা",
            "noIncomeLimit": "কোনো বাধ্যতামূলক সীমা নাই",
            "standardMarginMoney": "প্ৰকল্প ব্যয়ৰ 5% - 10%",
            "noCollateral": "কোনো বন্ধকীৰ প্ৰয়োজন নাই (CGTMSE গেৰাণ্টি)",
            "bankAssisted": "চেনেল অংশীদাৰ / বেংক সহায়ক",
            "directOnlinePortal": "পোনপটীয়া অনলাইন পৰ্টেল",
            "channelPartner": "চেনেল অংশীদাৰ / সংস্থা",
            "noCreditWelfare": "নহয় — অনুদান / ৰাজসাহায্য / কল্যাণমূলক আঁচনি"
        }
    }
}

def deep_merge(target, src):
    for k, v in src.items():
        if isinstance(v, dict):
            if k not in target or not isinstance(target[k], dict):
                target[k] = {}
            deep_merge(target[k], v)
        else:
            target[k] = v

def run():
    print("Applying comprehensive translations across all 10 non-English locales...")
    for lang, pack in REGIONAL_TRANSLATIONS.items():
        file_path = os.path.join(LOCALES_DIR, f"{lang}.json")
        if not os.path.exists(file_path):
            continue

        with open(file_path, "r", encoding="utf-8") as f:
            target_data = json.load(f)

        deep_merge(target_data, pack)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(target_data, f, ensure_ascii=False, indent=2)

        print(f"Applied compare & common translations for {lang}.json")

if __name__ == "__main__":
    run()
